interface ITranslationsCollection {
  [token: string]: [string, string, string, string, string, string, string, string];
}

const moveNames: ITranslationsCollection = {
  '001': [
    '1000まんボルト (Senman Volt)',
    '10,000,000 Volt Thunderbolt',
    'Tausendfacher Donnerblitz',
    'Gigarrayo Fulminante',
    'Giga-Tonnerre',
    'Iperfulmine',
    '',
    '',
  ],
  '002': ['すいとる (Suitoru)', 'Absorb', 'Absorber', 'Absorber', 'Vol-Vie', 'Assorbimento', '', ''],
  '003': ['アクセルロック (Accel Rock)', 'Accelerock', 'Turbofelsen', 'Roca Veloz', 'Vif Roc', 'Rocciarapida', '', ''],
  '004': ['ようかいえき (Yōkaieki)', 'Acid', 'Säure', 'Ácido', 'Acide', 'Acido', '', ''],
  '005': ['とける (Tokeru)', 'Acid Armor', 'Säurepanzer', 'Armadura Ácida', 'Acidarmure', 'Scudo Acido', '', ''],
  '006': [
    'アシッドポイズンデリート (Acid Poison Delete)',
    'Acid Downpour',
    'Vernichtender Säureregen',
    'Diluvio Corrosivo',
    'Déluge Causti-Toxique',
    'Acidiluvio Corrosivo',
    '',
    '',
  ],
  '007': ['アシッドボム (Acid Bomb)', 'Acid Spray', 'Säurespeier', 'Bomba Ácida', 'Bombe Acide', 'Acidobomba', '', ''],
  '008': ['アクロバット (Acrobat)', 'Acrobatics', 'Akrobatik', 'Acróbata', 'Acrobatie', 'Acrobazia', '', ''],
  '009': [
    'つぼをつく (Tsubo wo Tsuku)',
    'Acupressure',
    'Akupressur',
    'Acupresión',
    'Acupression',
    'Acupressione',
    '',
    '',
  ],
  '010': ['つばめがえし (Tsubame Gaeshi)', 'Aerial Ace', 'Aero-Ass', 'Golpe Aéreo', 'Aéropique', 'Aeroassalto', '', ''],
  '011': ['エアロブラスト (Aeroblast)', 'Aeroblast', 'Luftstoß', 'Aerochorro', 'Aéroblast', 'Aerocolpo', '', ''],
  '012': ['おさきにどうぞ (Osaki ni Dōzo)', 'After You', 'Galanterie', 'Cede Paso', 'Après Vous', 'Cortesia', '', ''],
  '013': ['こうそくいどう (Kōsoku Idō)', 'Agility', 'Agilität', 'Agilidad', 'Hâte', 'Agilità', '', ''],
  '014': ['エアカッター (Air Cutter)', 'Air Cutter', 'Windschnitt', 'Aire Afilado', "Tranch'Air", 'Aerasoio', '', ''],
  '015': ['エアスラッシュ (Air Slash)', 'Air Slash', 'Luftschnitt', 'Tajo Aéreo', "Lame d'Air", 'Eterelama', '', ''],
  '016': [
    '全力無双激烈拳 (Zenryoku Musō Gekiretsu Ken)',
    'All-Out Pummeling',
    'Fulminante Faustschläge',
    'Ráfaga Demoledora',
    'Combo Hyper-Furie',
    'Iperscarica Furiosa',
    '',
    '',
  ],
  '017': [
    'サイドチェンジ (Side Change)',
    'Ally Switch',
    'Seitentausch',
    'Cambio Banda',
    'Interversion',
    'Cambiaposto',
    '',
    '',
  ],
  '018': ['ドわすれ (Dowasure)', 'Amnesia', 'Amnesie', 'Amnesia', 'Amnésie', 'Amnesia', '', ''],
  '019': [
    'アンカーショット (Anchor Shot)',
    'Anchor Shot',
    'Ankerschuss',
    'Anclaje',
    'Ancrage',
    "Colpo d'Ancora",
    '',
    '',
  ],
  '020': [
    'げんしのちから (Genshi no Chikara)',
    'Ancient Power',
    'Antik-Kraft',
    'Poder Pasado',
    'Pouvoir Antique',
    'Forzantica',
    '',
    '',
  ],
  '021': ['アクアジェット (Aqua Jet)', 'Aqua Jet', 'Wasserdüse', 'Acua Jet', 'Aqua-Jet', 'Acquagetto', '', ''],
  '022': ['アクアリング (Aqua Ring)', 'Aqua Ring', 'Wasserring', 'Acua Aro', 'Anneau Hydro', 'Acquanello', '', ''],
  '023': ['アクアテール (Aqua Tail)', 'Aqua Tail', 'Nassschweif', 'Acua Cola', 'Hydroqueue', 'Idrondata', '', ''],
  '024': ['つっぱり (Tsuppari)', 'Arm Thrust', 'Armstoß', 'Empujón', 'Cogne', 'Sberletese', '', ''],
  '025': [
    'アロマセラピー (Aromatherapy)',
    'Aromatherapy',
    'Aromakur',
    'Aromaterapia',
    'Aromathérapi',
    'Aromaterapia',
    '',
    '',
  ],
  '026': [
    'アロマミスト (Aroma Mist)',
    'Aromatic Mist',
    'Duftwolke',
    'Niebla Aromática',
    'Brume Capiteuse',
    'Nebularoma',
    '',
    '',
  ],
  '027': ['ねこのて (Neko no Te)', 'Assist', 'Zuschuss', 'Ayuda', 'Assistance', 'Assistente', '', ''],
  '028': ['ダメおし (Dame Oshi)', 'Assurance', 'Gewissheit', 'Buena Baza', 'Assurance', 'Garanzia', '', ''],
  '029': ['おどろかす (Odorokasu)', 'Astonish', 'Erstauner', 'Impresionar', 'Étonnement', 'Sgomento', '', ''],
  '030': [
    'こうげきしれい (Kōgeki Shirei)',
    'Attack Order',
    'Schlagbefehl',
    'Al Ataque',
    'Appel Attak',
    'Comandourto',
    '',
    '',
  ],
  '031': ['メロメロ (Meromero)', 'Attract', 'Anziehung', 'Atracción', 'Attraction', 'Attrazione', '', ''],
  '032': ['はどうだん (Hadōdan)', 'Aura Sphere', 'Aurasphäre', 'Esfera Aural', 'Aurasphère', 'Forzasfera', '', ''],
  '033': [
    'オーロラビーム (Aurora Beam)',
    'Aurora Beam',
    'Aurorastrahl',
    'Rayo Aurora',
    'Onde Boréale',
    'Raggiaurora',
    '',
    '',
  ],
  '034': [
    'オーロラベール (Aurora Veil)',
    'Aurora Veil',
    'Auroraschleier',
    'Velo Aurora',
    'Voile Aurore',
    'Velaurora',
    '',
    '',
  ],
  '035': ['ボディパージ (Body Purge)', 'Autotomize', 'Autotomie', 'Aligerar', 'Allègement', 'Sganciapesi', '', ''],
  '036': ['ゆきなだれ (Yuki Nadare)', 'Avalanche', 'Lawine', 'Alud', 'Avalanche', 'Slavina', '', ''],
  '037': [
    'つぶらなひとみ (Tsuburana Hitomi)',
    'Baby-Doll Eyes',
    'Kulleraugen',
    'Ojitos Tiernos',
    'Regard Touchant',
    'Occhioni Teneri',
    '',
    '',
  ],
  '038': [
    '(Baddy Bad)',
    '(Baddy Bad)',
    '(Baddy Bad)',
    '(Baddy Bad)',
    '(Baddy Bad)',
    '(Baddy Bad)',
    '(Baddy Bad)',
    '(Baddy Bad)',
  ],
  '039': ['トーチカ (Tochka)', 'Baneful Bunker', 'Bunker', 'Búnker', 'Blockhaus', 'Fortino', '', ''],
  '040': ['たまなげ (Tamanage)', 'Barrage', 'Stakkato', 'Presa', 'Pilonnage', 'Attacco Pioggia', '', ''],
  '041': ['バリアー (Barrier)', 'Barrier', 'Barriere', 'Barrera', 'Bouclier', 'Barriera', '', ''],
  '042': ['バトンタッチ (Baton Touch)', 'Baton Pass', 'Stafette', 'Relevo', 'Relais', 'Staffetta', '', ''],
  '043': [
    'くちばしキャノン (Kuchibashi Cannon)',
    'Beak Blast',
    'Schnabelkanone',
    'Pico Cañón',
    'Bec-Canon',
    'Cannonbecco',
    '',
    '',
  ],
  '044': ['ふくろだたき (Fukurodataki)', 'Beat Up', 'Prügler', 'Paliza', 'Baston', 'Picchiaduro', '', ''],
  '045': ['ゲップ (Geppu)', 'Belch', 'Rülpser', 'Eructo', 'Éructation', 'Rutto', '', ''],
  '046': ['はらだいこ (Haradaiko)', 'Belly Drum', 'Bauchtrommel', 'Tambor', 'Cognobidon', 'Panciamburo', '', ''],
  '047': ['ギフトパス (Gift Pass)', 'Bestow', 'Offerte', 'Ofrenda', 'Passe-Cadeau', 'Cediregalo', '', ''],
  '048': ['がまん (Gaman)', 'Bide', 'Geduld', 'Venganza', 'Patience', 'Pazienza', '', ''],
  '049': ['しめつける (Shimetsukeru)', 'Bind', 'Klammergriff', 'Atadura', 'Étreinte', 'Legatutto', '', ''],
  '050': ['かみつく (Kamitsuku)', 'Bite', 'Biss', 'Mordisco', 'Morsure', 'Morso', '', ''],
  '051': [
    'ブラックホールイクリプス (Black Hole Eclipse)',
    'Black Hole Eclipse',
    'Schwarzes Loch des Grauens',
    'Agujero Negro Aniquilador',
    'Trou Noir des Ombres',
    'Buco Nero del Non Ritorno',
    '',
    '',
  ],
  '052': [
    'ブラストバーン (Blast Burn)',
    'Blast Burn',
    'Lohekanonade',
    'Anillo Ígneo',
    'Rafale Feu',
    'Incendio',
    '',
    '',
  ],
  '053': [
    'ブレイズキック (Blaze Kick)',
    'Blaze Kick',
    'Feuerfeger',
    'Patada Ígnea',
    'Pied Brûleur',
    'Calciardente',
    '',
    '',
  ],
  '054': ['ふぶき (Fubuki)', 'Blizzard', 'Blizzard', 'Ventisca', 'Blizzard', 'Bora', '', ''],
  '055': ['とおせんぼう (Tōsenbō)', 'Block', 'Rückentzug', 'Bloqueo', 'Barrage', 'Blocco', '', ''],
  '056': [
    'ブルームシャインエクストラ (Bloom Shine Extra)',
    'Bloom Doom',
    'Brillante Blütenpracht',
    'Megatón Floral',
    'Pétalexplosion Éblouissante',
    'Floriscoppio Sfolgorante',
    '',
    '',
  ],
  '057': ['あおいほのお (Aoi Honō)', 'Blue Flare', 'Blauflammen', 'Llama Azul', 'Flamme Bleue', 'Fuocoblu', '', ''],
  '058': ['のしかかり (Noshikakari)', 'Body Slam', 'Bodyslam', 'Golpe Cuerpo', 'Plaquage', 'Corposcontro', '', ''],
  '059': ['らいげき (Raigeki)', 'Bolt Strike', 'Blitzschlag', 'Ataque Fulgor', 'Charge Foudre', 'Lucesiluro', '', ''],
  '060': ['ホネこんぼう (Hone Konbō)', 'Bone Club', 'Knochenkeule', 'Hueso Palo', "Massd'Os", 'Ossoclava', '', ''],
  '061': ['ボーンラッシュ (Bone Rush)', 'Bone Rush', 'Knochenhatz', 'Ataque Óseo', 'Charge-Os', 'Ossoraffica', '', ''],
  '062': [
    'ホネブーメラン (Hone Boomerang)',
    'Bonemerang',
    'Knochmerang',
    'Huesomerang',
    'Osmerang',
    'Ossomerang',
    '',
    '',
  ],
  '063': ['ばくおんぱ (Bakuonpa)', 'Boomburst', 'Überschallknall', 'Estruendo', 'Bang Sonique', 'Ondaboato', '', ''],
  '064': ['とびはねる (Tobihaneru)', 'Bounce', 'Sprungfeder', 'Bote', 'Rebond', 'Rimbalzo', '', ''],
  '065': [
    '(Bouncy Bubble)',
    '(Bouncy Bubble)',
    '(Bouncy Bubble)',
    '(Bouncy Bubble)',
    '(Bouncy Bubble)',
    '(Bouncy Bubble)',
    '(Bouncy Bubble)',
    '(Bouncy Bubble)',
  ],
  '066': ['ブレイブバード (Brave Bird)', 'Brave Bird', 'Sturzflug', 'Pájaro Osado', 'Rapace', 'Baldeali', '', ''],
  '067': [
    'ウルトラダッシュアタック (Ultra Dash Attack)',
    'Breakneck Blitz',
    'Hyper-Sprintangriff',
    'Carrera Arrolladora',
    'Turbo-Charge Bulldozer',
    'Carica Travolgente',
    '',
    '',
  ],
  '068': ['かわらわり (Kawarawari)', 'Brick Break', 'Durchbruch', 'Demolición', 'Casse-Brique', 'Breccia', '', ''],
  '069': ['しおみず (Shiomizu)', 'Brine', 'Lake', 'Salmuera', 'Saumure', 'Acquadisale', '', ''],
  '070': ['ぶんまわす (Bunmawasu)', 'Brutal Swing', 'Wirbler', 'Giro Vil', 'Centrifugifle', 'Vorticolpo', '', ''],
  '071': ['あわ (Awa)', 'Bubble', 'Blubber', 'Burbuja', 'Écume', 'Bolla', '', ''],
  '072': [
    'バブルこうせん (Bubble Kōsen)',
    'Bubble Beam',
    'Blubbstrahl',
    'Rayo Burbuja',
    "Bulles d'O",
    'Bollaraggio',
    '',
    '',
  ],
  '073': ['むしくい (Mushi Kui)', 'Bug Bite', 'Käferbiss', 'Picadura', 'Piqûre', 'Coleomorso', '', ''],
  '074': ['むしのさざめき (Mushi no Sazameki)', 'Bug Buzz', 'Käfergebrumm', 'Zumbido', 'Bourdon', 'Ronzio', '', ''],
  '075': ['ビルドアップ (Build-Up)', 'Bulk Up', 'Protzer', 'Corpulencia', 'Gonflette', 'Granfisico', '', ''],
  '076': ['じならし (Jinarashi)', 'Bulldoze', 'Dampfwalze', 'Terratemblor', 'Piétisol', 'Battiterra', '', ''],
  '077': [
    'バレットパンチ (Bullet Punch)',
    'Bullet Punch',
    'Patronenhieb',
    'Puño Bala',
    'Pisto-Poing',
    'Pugnoscarica',
    '',
    '',
  ],
  '078': [
    'タネマシンガン (Tane Machine Gun)',
    'Bullet Seed',
    'Kugelsaat',
    'Recurrente',
    'Balle Graine',
    'Semitraglia',
    '',
    '',
  ],
  '079': ['もえつきる (Moetsukiru)', 'Burn Up', 'Ausbrennen', 'Llama Final', 'Flamme Ultime', 'Ultima Fiamma', '', ''],
  '080': [
    '(Buzzy Buzz)',
    '(Buzzy Buzz)',
    '(Buzzy Buzz)',
    '(Buzzy Buzz)',
    '(Buzzy Buzz)',
    '(Buzzy Buzz)',
    '(Buzzy Buzz)',
    '(Buzzy Buzz)',
  ],
  '081': ['めいそう (Meisō)', 'Calm Mind', 'Gedankengut', 'Paz Mental', 'Plénitude', 'Calmamente', '', ''],
  '082': ['ほごしょく (Hogoshoku)', 'Camouflage', 'Tarnung', 'Camuflaje', 'Camouflage', 'Camuffamento', '', ''],
  '083': ['ゆうわく (Yūwaku)', 'Captivate', 'Liebreiz', 'Seducción', 'Séduction', 'Incanto', '', ''],
  '084': [
    'ひっさつのピカチュート (Hissatsu no Pikachoot)',
    'Catastropika',
    'Perfektes Pika-Projektil',
    'Pikavoltio Letal',
    'Pikachute Foudroyante',
    'Super Pikaboom',
    '',
    '',
  ],
  '085': ['おいわい (Oiwai)', 'Celebrate', 'Ehrentag', 'Celebración', 'Célébration', 'Auguri', '', ''],
  '086': ['じゅうでん (Jūden)', 'Charge', 'Ladevorgang', 'Carga', 'Chargeur', 'Sottocarica', '', ''],
  '087': [
    'チャージビーム (Charge Beam)',
    'Charge Beam',
    'Ladestrahl',
    'Rayo Carga',
    'Rayon Chargé',
    'Raggioscossa',
    '',
    '',
  ],
  '088': ['あまえる (Amaeru)', 'Charm', 'Charme', 'Encanto', 'Charme', 'Fascino', '', ''],
  '089': ['おしゃべり (Oshaberi)', 'Chatter', 'Geschwätz', 'Cháchara', 'Babil', 'Schiamazzo', '', ''],
  '090': ['なしくずし (Nashikuzushi)', 'Chip Away', 'Zermürben', 'Guardia Baja', 'Attrition', 'Insidia', '', ''],
  '091': ['ともえなげ (Tomoenage)', 'Circle Throw', 'Überkopfwurf', 'Llave Giro', 'Projection', 'Ribaltiro', '', ''],
  '092': ['からではさむ (Kara de Hasamu)', 'Clamp', 'Schnapper', 'Tenaza', 'Claquoir', 'Tenaglia', '', ''],
  '093': [
    'スケイルノイズ (Scale Noise)',
    'Clanging Scales',
    'Schuppenrasseln',
    'Fragor Escamas',
    'Vibrécaille',
    'Clamorsquame',
    '',
    '',
  ],
  '094': [
    'ブレイジングソウルビート (Blazing Soulbeat)',
    'Clangorous Soulblaze',
    'Rasselnder Seelentanz',
    'Estruendo Implacable',
    'Dracacophonie Flamboyante',
    'Dracofonia Divampante',
    '',
    '',
  ],
  '095': ['クリアスモッグ (Clear Smog)', 'Clear Smog', 'Klärsmog', 'Niebla Clara', 'Bain de Smog', 'Pulifumo', '', ''],
  '096': ['インファイト (In-Fight)', 'Close Combat', 'Nahkampf', 'A Bocajarro', 'Close Combat', 'Zuffa', '', ''],
  '097': ['とぐろをまく (Toguro wo Maku)', 'Coil', 'Einrollen', 'Enrosque', 'Enroulement', 'Arrotola', '', ''],
  '098': [
    'れんぞくパンチ (Renzoku Punch)',
    'Comet Punch',
    'Kometenhieb',
    'Puño Cometa',
    'Poing Comète',
    'Cometapugno',
    '',
    '',
  ],
  '099': [
    'ないしょばなし (Naisho-banashi)',
    'Confide',
    'Vertrauenssache',
    'Confidencia',
    'Confidence',
    'Confidenza',
    '',
    '',
  ],
  '100': [
    'あやしいひかり (Ayashī Hikari)',
    'Confuse Ray',
    'Konfustrahl',
    'Rayo Confuso',
    'Onde Folie',
    'Stordiraggio',
    '',
    '',
  ],
  '101': ['ねんりき (Nenriki)', 'Confusion', 'Konfusion', 'Confusión', 'Choc Mental', 'Confusione', '', ''],
  '102': [
    'からみつく (Karamitsuku)',
    'Constrict',
    'Umklammerung',
    'Restricción',
    'Constriction',
    'Limitazione',
    '',
    '',
  ],
  '103': [
    "ワールドエンドフォール (World's End Fall)",
    'Continental Crush',
    'Apokalyptische Steinpresse',
    'Aplastamiento Gigalítico',
    'Apocalypse Gigalithique',
    'Gigamacigno Polverizzante',
    '',
    '',
  ],
  '104': ['テクスチャー (Texture)', 'Conversion', 'Umwandlung', 'Conversión', 'Conversion', 'Conversione', '', ''],
  '105': [
    'テクスチャー２ (Texture 2)',
    'Conversion 2',
    'Umwandlung2',
    'Conversión2',
    'Conversion2',
    'Conversione2',
    '',
    '',
  ],
  '106': ['まねっこ (Manekko)', 'Copycat', 'Imitator', 'Copión', 'Photocopie', 'Copione', '', ''],
  '107': [
    'コアパニッシャー (Core Punisher)',
    'Core Enforcer',
    'Sanktionskern',
    'Núcleo Castigo',
    'Sanction Suprême',
    'Nucleocastigo',
    '',
    '',
  ],
  '108': [
    '超絶螺旋連撃 (Chōzetsu Rasen Rengeki)',
    'Corkscrew Crash',
    'Turbo-Spiralkombo',
    'Hélice Trepanadora',
    'Vrille Maximum',
    'Spirale Perforante',
    '',
    '',
  ],
  '109': [
    'コスモパワー (Cosmo Power)',
    'Cosmic Power',
    'Kosmik-Kraft',
    'Masa Cósmica',
    'Force Cosmik',
    'Cosmoforza',
    '',
    '',
  ],
  '110': [
    'コットンガード (Cotton Guard)',
    'Cotton Guard',
    'Watteschild',
    'Rizo Algodón',
    'Cotogarde',
    'Cotonscudo',
    '',
    '',
  ],
  '111': [
    'わたほうし (Wata Hōshi)',
    'Cotton Spore',
    'Baumwollsaat',
    'Esporagodón',
    'Spore Coton',
    'Cottonspora',
    '',
    '',
  ],
  '112': ['カウンター (Counter)', 'Counter', 'Konter', 'Contraataque', 'Riposte', 'Contrattacco', '', ''],
  '113': ['ほしがる (Hoshigaru)', 'Covet', 'Bezirzer', 'Antojo', 'Implore', 'Supplica', '', ''],
  '114': [
    'クラブハンマー (Crab Hammer)',
    'Crabhammer',
    'Krabbhammer',
    'Martillazo',
    'Pince-Masse',
    'Martellata',
    '',
    '',
  ],
  '115': [
    'トリックガード (Trick Guard)',
    'Crafty Shield',
    'Trickschutz',
    'Truco Defensa',
    'Vigilance',
    'Truccodifesa',
    '',
    '',
  ],
  '116': ['クロスチョップ (Cross Chop)', 'Cross Chop', 'Kreuzhieb', 'Tajo Cruzado', 'Coup-Croix', 'Incrocolpo', '', ''],
  '117': [
    'クロスポイズン (Cross Poison)',
    'Cross Poison',
    'Giftstreich',
    'Veneno X',
    'Poison-Croix',
    'Velenocroce',
    '',
    '',
  ],
  '118': ['かみくだく (Kamikudaku)', 'Crunch', 'Knirscher', 'Triturar', 'Mâchouille', 'Sgranocchio', '', ''],
  '119': [
    'ブレイククロー (Break Claw)',
    'Crush Claw',
    'Zermalmklaue',
    'Garra Brutal',
    'Éclate Griffe',
    'Tritartigli',
    '',
    '',
  ],
  '120': ['にぎりつぶす (Nigiri Tsubusu)', 'Crush Grip', 'Quetschgriff', 'Agarrón', 'Presse', 'Sbriciolmano', '', ''],
  '121': ['のろい (Noroi)', 'Curse', 'Fluch', 'Maldición', 'Malédiction', 'Maledizione', '', ''],
  '122': ['いあいぎり (Iai Giri)', 'Cut', 'Zerschneider', 'Corte', 'Coupe', 'Taglio', '', ''],
  '123': [
    'あくのはどう (Aku no Hadō)',
    'Dark Pulse',
    'Finsteraura',
    'Pulso Umbrío',
    'Vibrobscur',
    'Neropulsar',
    '',
    '',
  ],
  '124': ['ダークホール (Dark Hole)', 'Dark Void', 'Schlummerort', 'Brecha Negra', 'Trou Noir', 'Vuototetro', '', ''],
  '125': [
    'DDラリアト (DD Lariat)',
    'Darkest Lariat',
    'Dark Lariat',
    'Lariat Oscuro',
    'Dark Lariat',
    'Braccioteso',
    '',
    '',
  ],
  '126': [
    'マジカルシャイン (Magical Shine)',
    'Dazzling Gleam',
    'Zauberschein',
    'Brillo Mágico',
    'Éclat Magique',
    'Magibrillio',
    '',
    '',
  ],
  '127': [
    'ぼうぎょしれい (Bōgyo Shirei)',
    'Defend Order',
    'Blockbefehl',
    'A Defender',
    'Appel Défense',
    'Comandoscudo',
    '',
    '',
  ],
  '128': ['まるくなる (Marukunaru)', 'Defense Curl', 'Einigler', 'Rizo Defensa', "Boul'Armure", 'Ricciolscudo', '', ''],
  '129': ['きりばらい (Kiribarai)', 'Defog', 'Auflockern', 'Despejar', 'Anti-Brume', 'Scacciabruma', '', ''],
  '130': [
    'みちづれ (Michizure)',
    'Destiny Bond',
    'Abgangsbund',
    'Mismo Destino',
    'Prélèvem. Destin',
    'Destinobbligato',
    '',
    '',
  ],
  '131': ['みきり (Mikiri)', 'Detect', 'Scanner', 'Detección', 'Détection', 'Individua', '', ''],
  '132': [
    'アルティメットドラゴンバーン (Ultimate Dragon Burn)',
    'Devastating Drake',
    'Drastisches Drachendröhnen',
    'Dracoaliento Devastador',
    'Chaos Draconique',
    'Dragoschianto Finale',
    '',
    '',
  ],
  '133': [
    'ダイヤストーム (Dia Storm)',
    'Diamond Storm',
    'Diamantsturm',
    'Torm. Diamantes',
    'Orage Adamantin',
    'Diamantempesta',
    '',
    '',
  ],
  '134': ['あなをほる (Ana wo Horu)', 'Dig', 'Schaufler', 'Excavar', 'Tunnel', 'Fossa', '', ''],
  '135': ['かなしばり (Kanashibari)', 'Disable', 'Aussetzer', 'Anulación', 'Entrave', 'Inibitore', '', ''],
  '136': [
    'チャームボイス (Charm Voice)',
    'Disarming Voice',
    'Säuselstimme',
    'Voz Cautivadora',
    'Voix Enjôleuse',
    'Incantavoce',
    '',
    '',
  ],
  '137': ['ほうでん (Hōden)', 'Discharge', 'Ladungsstoß', 'Chispazo', "Coup d'Jus", 'Scarica', '', ''],
  '138': ['ダイビング (Diving)', 'Dive', 'Taucher', 'Buceo', 'Plongée', 'Sub', '', ''],
  '139': [
    'ピヨピヨパンチ (Piyopiyo Punch)',
    'Dizzy Punch',
    'Irrschlag',
    'Puño Mareo',
    'Uppercut',
    'Stordipugno',
    '',
    '',
  ],
  '140': [
    'はめつのねがい (Hametsu no Negai)',
    'Doom Desire',
    'Kismetwunsch',
    'Deseo Oculto',
    'Carnareket',
    'Obbliderio',
    '',
    '',
  ],
  '141': [
    'ダブルアタック (Double Attack)',
    'Double Hit',
    'Doppelschlag',
    'Doble Golpe',
    'Coup Double',
    'Doppiosmash',
    '',
    '',
  ],
  '142': [
    '(Double Iron Bash)',
    '(Double Iron Bash)',
    '(Double Iron Bash)',
    '(Double Iron Bash)',
    '(Double Iron Bash)',
    '(Double Iron Bash)',
    '(Double Iron Bash)',
    '(Double Iron Bash)',
  ],
  '143': ['にどげり (Nidogeri)', 'Double Kick', 'Doppelkick', 'Doble Patada', 'Double Pied', 'Doppiocalcio', '', ''],
  '144': [
    'おうふくビンタ (Ōfuku Binta)',
    'Double Slap',
    'Duplexhieb',
    'Doble Bofetón',
    'Torgnoles',
    'Doppiasberla',
    '',
    '',
  ],
  '145': ['かげぶんしん (Kage Bunshin)', 'Double Team', 'Doppelteam', 'Doble Equipo', 'Reflet', 'Doppioteam', '', ''],
  '146': [
    'すてみタックル (Sutemi Tackle)',
    'Double-Edge',
    'Risikotackle',
    'Doble Filo',
    'Damoclès',
    'Sdoppiatore',
    '',
    '',
  ],
  '147': [
    'りゅうせいぐん (Ryūseigun)',
    'Draco Meteor',
    'Draco Meteor',
    'Cometa Draco',
    'Draco Météor',
    'Dragobolide',
    '',
    '',
  ],
  '148': [
    'ガリョウテンセイ (Garyō Tensei)',
    'Dragon Ascent',
    'Zenitstürmer',
    'Ascenso Draco',
    'Draco Ascension',
    'Ascesa del Drago',
    '',
    '',
  ],
  '149': [
    'りゅうのいぶき (Ryū no Ibuki)',
    'Dragon Breath',
    'Feuerodem',
    'Dragoaliento',
    'Dracosouffle',
    'Dragospiro',
    '',
    '',
  ],
  '150': [
    'ドラゴンクロー (Dragon Claw)',
    'Dragon Claw',
    'Drachenklaue',
    'Garra Dragón',
    'Dracogriffe',
    'Dragartigli',
    '',
    '',
  ],
  '151': [
    'りゅうのまい (Ryū no Mai)',
    'Dragon Dance',
    'Drachentanz',
    'Danza Dragón',
    'Danse Draco',
    'Dragodanza',
    '',
    '',
  ],
  '152': [
    'ドラゴンハンマー (Dragon Hammer)',
    'Dragon Hammer',
    'Drachenhammer',
    'Martillo Dragón',
    'Draco-Marteau',
    'Marteldrago',
    '',
    '',
  ],
  '153': [
    'りゅうのはどう (Ryū no Hadō)',
    'Dragon Pulse',
    'Drachenpuls',
    'Pulso Dragón',
    'Dracochoc',
    'Dragopulsar',
    '',
    '',
  ],
  '154': [
    'りゅうのいかり (Ryū no Ikari)',
    'Dragon Rage',
    'Drachenwut',
    'Furia Dragón',
    'Draco-Rage',
    'Ira di Drago',
    '',
    '',
  ],
  '155': [
    'ドラゴンダイブ (Dragon Dive)',
    'Dragon Rush',
    'Drachenstoß',
    'Carga Dragón',
    'Dracocharge',
    'Dragofuria',
    '',
    '',
  ],
  '156': [
    'ドラゴンテール (Dragon Tail)',
    'Dragon Tail',
    'Drachenrute',
    'Cola Dragón',
    'Draco-Queue',
    'Codadrago',
    '',
    '',
  ],
  '157': [
    'ドレインパンチ (Drain Punch)',
    'Drain Punch',
    'Ableithieb',
    'Puño Drenaje',
    'Vampipoing',
    'Assorbipugno',
    '',
    '',
  ],
  '158': [
    'ドレインキッス (Drain Kiss)',
    'Draining Kiss',
    'Diebeskuss',
    'Beso Drenaje',
    'Vampibaiser',
    'Assorbibacio',
    '',
    '',
  ],
  '159': ['ゆめくい (Yume Kui)', 'Dream Eater', 'Traumfresser', 'Come Sueños', 'Dévorêve', 'Mangiasogni', '', ''],
  '160': [
    'ドリルくちばし (Drill Kuchibashi)',
    'Drill Peck',
    'Bohrschnabel',
    'Pico Taladro',
    'Bec Vrille',
    'Perforbecco',
    '',
    '',
  ],
  '161': ['ドリルライナー (Drill Liner)', 'Drill Run', 'Schlagbohrer', 'Taladradora', 'Tunnelier', 'Giravvita', '', ''],
  '162': [
    'ダブルチョップ (Double Chop)',
    'Dual Chop',
    'Doppelhieb',
    'Golpe Bis',
    'Double Baffe',
    'Doppiocolpo',
    '',
    '',
  ],
  '163': [
    'ばくれつパンチ (Bakuretsu Punch)',
    'Dynamic Punch',
    'Wuchtschlag',
    'Puño Dinámico',
    'Dynamopoing',
    'Dinamipugno',
    '',
    '',
  ],
  '164': [
    'だいちのちから (Daichi no Chikara)',
    'Earth Power',
    'Erdkräfte',
    'Tierra Viva',
    'Telluriforce',
    'Geoforza',
    '',
    '',
  ],
  '165': ['じしん (Jishin)', 'Earthquake', 'Erdbeben', 'Terremoto', 'Séisme', 'Terremoto', '', ''],
  '166': ['エコーボイス (Echo Voice)', 'Echoed Voice', 'Widerhall', 'Eco Voz', 'Écho', 'Echeggiavoce', '', ''],
  '167': [
    'かいでんぱ (Kaidenpa)',
    'Eerie Impulse',
    'Mystowellen',
    'Onda Anómala',
    'Ondes Étranges',
    'Elettromistero',
    '',
    '',
  ],
  '168': ['タマゴばくだん (Tamago Bakudan)', 'Egg Bomb', 'Eierbombe', 'Bomba Huevo', "Bomb'Œuf", 'Uovobomba', '', ''],
  '169': [
    'エレキフィールド (Elec Field)',
    'Electric Terrain',
    'Elektrofeld',
    'Campo Eléctrico',
    'Champ Électrifié',
    'Campo Elettrico',
    '',
    '',
  ],
  '170': [
    'そうでん (Sōden)',
    'Electrify',
    'Elektrifizierung',
    'Electrificación',
    'Électrisation',
    'Elettrocontagio',
    '',
    '',
  ],
  '171': [
    'エレキボール (Elec Ball)',
    'Electro Ball',
    'Elektroball',
    'Bola Voltio',
    'Boule Élek',
    'Energisfera',
    '',
    '',
  ],
  '172': ['エレキネット (Elec Net)', 'Electroweb', 'Elektronetz', 'Electrotela', 'Toile Élek', 'Elettrotela', '', ''],
  '173': ['さしおさえ (Sashiosae)', 'Embargo', 'Itemsperre', 'Embargo', 'Embargo', 'Divieto', '', ''],
  '174': ['ひのこ (Hinoko)', 'Ember', 'Glut', 'Ascuas', 'Flammèche', 'Braciere', '', ''],
  '175': ['アンコール (Encore)', 'Encore', 'Zugabe', 'Otra Vez', 'Encore', 'Ripeti', '', ''],
  '176': ['がむしゃら (Gamushara)', 'Endeavor', 'Notsituation', 'Esfuerzo', 'Effort', 'Rimonta', '', ''],
  '177': ['こらえる (Koraeru)', 'Endure', 'Ausdauer', 'Aguante', 'Ténacité', 'Resistenza', '', ''],
  '178': [
    'エナジーボール (Energy Ball)',
    'Energy Ball',
    'Energieball',
    'Energibola',
    'Éco-Sphère',
    'Energipalla',
    '',
    '',
  ],
  '179': ['なかまづくり (Nakama Zukuri)', 'Entrainment', 'Zwango', 'Danza Amiga', 'Ten-danse', 'Saltamicizia', '', ''],
  '180': ['ふんか (Funka)', 'Eruption', 'Eruption', 'Estallido', 'Éruption', 'Eruzione', '', ''],
  '181': ['だいばくはつ (Dai Bakuhatsu)', 'Explosion', 'Explosion', 'Explosión', 'Explosion', 'Esplosione', '', ''],
  '182': [
    'じんつうりき (Jintsūriki)',
    'Extrasensory',
    'Sondersensor',
    'Paranormal',
    'Extrasenseur',
    'Extrasenso',
    '',
    '',
  ],
  '183': [
    'ナインエボルブースト (Nine Evol Boost)',
    'Extreme Evoboost',
    'Macht der Neun',
    'Novena Potencia',
    'Neuf pour Un',
    'Potenziamento Eevolutivo',
    '',
    '',
  ],
  '184': [
    'しんそく (Shinsoku)',
    'Extreme Speed',
    'Turbotempo',
    'Veloc. Extrema',
    'Vitesse Extrême',
    'Extrarapido',
    '',
    '',
  ],
  '185': ['からげんき (Karagenki)', 'Facade', 'Fassade', 'Imagen', 'Façade', 'Facciata', '', ''],
  '186': [
    'フェアリーロック (Fairy Lock)',
    'Fairy Lock',
    'Feenschloss',
    'Cerrojo Feérico',
    'Verrou Enchanté',
    'Blocco Fatato',
    '',
    '',
  ],
  '187': [
    'ようせいのかぜ (Yōsei no Kaze)',
    'Fairy Wind',
    'Feenbrise',
    'Viento Feérico',
    'Vent Féérique',
    'Vento di Fata',
    '',
    '',
  ],
  '188': ['ねこだまし (Nekodamashi)', 'Fake Out', 'Mogelhieb', 'Sorpresa', 'Bluff', 'Bruciapelo', '', ''],
  '189': ['うそなき (Uso Naki)', 'Fake Tears', 'Trugträne', 'Llanto Falso', 'Croco Larme', 'Falselacrime', '', ''],
  '190': ['みねうち (Mineuchi)', 'False Swipe', 'Trugschlag', 'Falsotortazo', 'Faux-Chage', 'Falsofinale', '', ''],
  '191': [
    'フェザーダンス (Feather Dance)',
    'Feather Dance',
    'Daunenreigen',
    'Danza Pluma',
    'Danse-Plume',
    'Danzadipiume',
    '',
    '',
  ],
  '192': ['フェイント (Feint)', 'Feint', 'Offenlegung', 'Amago', 'Ruse', 'Fintoattacco', '', ''],
  '193': ['だましうち (Damashiuchi)', 'Feint Attack', 'Finte', 'Finta', 'Feinte', 'Finta', '', ''],
  '194': [
    'とどめばり (Todome-bari)',
    'Fell Stinger',
    'Stachelfinale',
    'Aguijón Letal',
    'Dard Mortel',
    'Pungiglione',
    '',
    '',
  ],
  '195': [
    'ほのおのまい (Honō no Mai)',
    'Fiery Dance',
    'Feuerreigen',
    'Danza Llama',
    'Danse du Feu',
    'Voldifuoco',
    '',
    '',
  ],
  '196': ['いのちがけ (Inochigake)', 'Final Gambit', 'Wagemut', 'Sacrificio', 'Tout ou Rien', 'Azzardo', '', ''],
  '197': ['だいもんじ (Dai Monji)', 'Fire Blast', 'Feuersturm', 'Llamarada', 'Déflagration', 'Fuocobomba', '', ''],
  '198': ['ほのおのキバ (Honō no Kiba)', 'Fire Fang', 'Feuerzahn', 'Colmillo Ígneo', 'Crocs Feu', 'Rogodenti', '', ''],
  '199': [
    'ほのおのムチ (Honō no Muchi)',
    'Fire Lash',
    'Feuerpeitsche',
    'Látigo Ígneo',
    'Fouet de Feu',
    'Frusta di Fuoco',
    '',
    '',
  ],
  '200': [
    'ほのおのちかい (Honō no Chikai)',
    'Fire Pledge',
    'Feuersäulen',
    'Voto Fuego',
    'Aire de Feu',
    'Fiammapatto',
    '',
    '',
  ],
  '201': [
    'ほのおのパンチ (Honō no Punch)',
    'Fire Punch',
    'Feuerschlag',
    'Puño Fuego',
    'Poing de Feu',
    'Fuocopugno',
    '',
    '',
  ],
  '202': ['ほのおのうず (Honō no Uzu)', 'Fire Spin', 'Feuerwirbel', 'Giro Fuego', 'Danse Flamme', 'Turbofuoco', '', ''],
  '203': [
    'であいがしら (Deaigashira)',
    'First Impression',
    'Überrumpler',
    'Escaramuza',
    'Escarmouche',
    'Schermaglia',
    '',
    '',
  ],
  '204': ['じわれ (Jiware)', 'Fissure', 'Geofissur', 'Fisura', 'Abîme', 'Abisso', '', ''],
  '205': ['じたばた (Jitabata)', 'Flail', 'Dreschflegel', 'Azote', 'Fléau', 'Flagello', '', ''],
  '206': [
    'はじけるほのお (Hajikeru Honō)',
    'Flame Burst',
    'Funkenflug',
    'Pirotecnia',
    'Rebondifeu',
    'Pirolancio',
    '',
    '',
  ],
  '207': [
    'ニトロチャージ (Nitro Charge)',
    'Flame Charge',
    'Nitroladung',
    'Nitrocarga',
    'Nitrocharge',
    'Nitrocarica',
    '',
    '',
  ],
  '208': [
    'かえんぐるま (Kaen Guruma)',
    'Flame Wheel',
    'Flammenrad',
    'Rueda Fuego',
    'Roue de Feu',
    'Ruotafuoco',
    '',
    '',
  ],
  '209': [
    'かえんほうしゃ (Kaen Hōsha)',
    'Flamethrower',
    'Flammenwurf',
    'Lanzallamas',
    'Lance-Flammes',
    'Lanciafiamme',
    '',
    '',
  ],
  '210': [
    'フレアドライブ (Flare Drive)',
    'Flare Blitz',
    'Flammenblitz',
    'Envite Ígneo',
    'Boutefeu',
    'Fuococarica',
    '',
    '',
  ],
  '211': ['フラッシュ (Flash)', 'Flash', 'Blitz', 'Destello', 'Flash', 'Flash', '', ''],
  '212': [
    'ラスターカノン (Luster Cannon)',
    'Flash Cannon',
    'Lichtkanone',
    'Foco Resplandor',
    'Luminocanon',
    'Cannonflash',
    '',
    '',
  ],
  '213': ['おだてる (Odateru)', 'Flatter', 'Schmeichler', 'Camelo', 'Flatterie', 'Adulazione', '', ''],
  '214': [
    'フルールカノン (Fleur Cannon)',
    'Fleur Cannon',
    'Kanonenbouquet',
    'Cañón Floral',
    'Canon Floral',
    'Cannonfiore',
    '',
    '',
  ],
  '215': ['なげつける (Nagetsukeru)', 'Fling', 'Schleuder', 'Lanzamiento', 'Dégommage', 'Lancio', '', ''],
  '216': [
    '(Floaty Fall)',
    '(Floaty Fall)',
    '(Floaty Fall)',
    '(Floaty Fall)',
    '(Floaty Fall)',
    '(Floaty Fall)',
    '(Floaty Fall)',
    '(Floaty Fall)',
  ],
  '217': [
    'フラワーヒール (Flower Heal)',
    'Floral Healing',
    'Florakur',
    'Cura Floral',
    'Soin Floral',
    'Cura Floreale',
    '',
    '',
  ],
  '218': [
    'フラワーガード (Flower Guard)',
    'Flower Shield',
    'Floraschutz',
    'Defensa Floral',
    'Garde Florale',
    'Fiordifesa',
    '',
    '',
  ],
  '219': ['そらをとぶ (Sora wo Tobu)', 'Fly', 'Fliegen', 'Vuelo', 'Vol', 'Volo', '', ''],
  '220': [
    'フライングプレス (Flying Press)',
    'Flying Press',
    'Flying Press',
    'Plancha Voladora',
    'Flying Press',
    'Schiacciatuffo',
    '',
    '',
  ],
  '221': ['きあいだま (Kiai Dama)', 'Focus Blast', 'Fokusstoß', 'Onda Certera', 'Exploforce', 'Focalcolpo', '', ''],
  '222': [
    'きあいだめ (Kiai Dame)',
    'Focus Energy',
    'Energiefokus',
    'Foco Energía',
    'Puissance',
    'Focalenergia',
    '',
    '',
  ],
  '223': [
    'きあいパンチ (Kiai Punch)',
    'Focus Punch',
    'Power-Punch',
    'Puño Certero',
    'Mitra-Poing',
    'Centripugno',
    '',
    '',
  ],
  '224': ['このゆびとまれ (Kono Yubi Tomare)', 'Follow Me', 'Spotlight', 'Señuelo', 'Par Ici', 'Sonoqui', '', ''],
  '225': ['はっけい (Hakkei)', 'Force Palm', 'Kraftwelle', 'Palmeo', 'Forte-Paume', 'Palmoforza', '', ''],
  '226': ['みやぶる (Miyaburu)', 'Foresight', 'Gesichte', 'Profecía', 'Clairvoyance', 'Preveggenza', '', ''],
  '227': [
    'もりののろい (Mori no Noroi)',
    "Forest's Curse",
    'Waldesfluch',
    'Condena Silvana',
    'Maléfice Sylvain',
    'Schiacciatuffo',
    '',
    '',
  ],
  '228': ['イカサマ (Ikasama)', 'Foul Play', 'Schmarotzer', 'Juego Sucio', 'Tricherie', 'Ripicca', '', ''],
  '229': [
    'フリーズボルト (Freeze Volt)',
    'Freeze Shock',
    'Frostvolt',
    'Rayo Gélido',
    'Éclair Gelé',
    'Elettrogelo',
    '',
    '',
  ],
  '230': [
    'フリーズドライ (Freeze Dry)',
    'Freeze-Dry',
    'Gefriertrockner',
    'Liofilización',
    'Lyophilisation',
    'Liofilizzazione',
    '',
    '',
  ],
  '231': [
    '(Freezy Frost)',
    '(Freezy Frost)',
    '(Freezy Frost)',
    '(Freezy Frost)',
    '(Freezy Frost)',
    '(Freezy Frost)',
    '(Freezy Frost)',
    '(Freezy Frost)',
  ],
  '232': [
    'ハードプラント (Hard Plant)',
    'Frenzy Plant',
    'Flora-Statue',
    'Planta Feroz',
    'Végé-Attak',
    'Radicalbero',
    '',
    '',
  ],
  '233': [
    'こおりのいぶき (Kōri no Ibuki)',
    'Frost Breath',
    'Eisesodem',
    'Vaho Gélido',
    'Souffle Glacé',
    'Alitogelido',
    '',
    '',
  ],
  '234': [
    'やつあたり (Yatsuatari)',
    'Frustration',
    'Frustration',
    'Frustración',
    'Frustration',
    'Frustrazione',
    '',
    '',
  ],
  '235': ['みだれづき (Midare Dzuki)', 'Fury Attack', 'Furienschlag', 'Ataque Furia', 'Furie', 'Furia', '', ''],
  '236': ['れんぞくぎり (Renzoku Giri)', 'Fury Cutter', 'Zornklinge', 'Cortefuria', 'Taillade', 'Tagliofuria', '', ''],
  '237': [
    'みだれひっかき (Midare Hikkaki)',
    'Fury Swipes',
    'Kratzfurie',
    'Golpes Furia',
    'Combo-Griffe',
    'Sfuriate',
    '',
    '',
  ],
  '238': [
    'クロスサンダー (Cross Thunder)',
    'Fusion Bolt',
    'Kreuzdonner',
    'Rayo Fusión',
    'Éclair Croix',
    'Incrotuono',
    '',
    '',
  ],
  '239': [
    'クロスフレイム (Cross Flame)',
    'Fusion Flare',
    'Kreuzflamme',
    'Llama Fusión',
    'Flamme Croix',
    'Incrofiamma',
    '',
    '',
  ],
  '240': ['みらいよち (Mirai Yochi)', 'Future Sight', 'Seher', 'Premonición', 'Prescience', 'Divinazione', '', ''],
  '241': ['いえき (Ieki)', 'Gastro Acid', 'Magensäfte', 'Bilis', 'Suc Digestif', 'Gastroacido', '', ''],
  '242': ['ギアソーサー (Gear Saucer)', 'Gear Grind', 'Klikkdiskus', 'Rueda Doble', 'Lancécrou', 'Ingracolpo', '', ''],
  '243': [
    'アシストギア (Assist Gear)',
    'Gear Up',
    'Hilfsmechanik',
    'Piñón Auxiliar',
    'Engrenage',
    'Marciainpiù',
    '',
    '',
  ],
  '244': [
    'オリジンズスーパーノヴァ (Origins Supernova)',
    'Genesis Supernova',
    'Supernova des Ursprungs',
    'Supernova Original',
    'Supernova Originelle',
    'Supernova delle Origini',
    '',
    '',
  ],
  '245': [
    'ジオコントロール (Geocontrol)',
    'Geomancy',
    'Geokontrolle',
    'Geocontrol',
    'Géo-Contrôle',
    'Geocontrollo',
    '',
    '',
  ],
  '246': [
    'ギガドレイン (Giga Drain)',
    'Giga Drain',
    'Gigasauger',
    'Gigadrenado',
    'Giga-Sangsue',
    'Gigassorbimento',
    '',
    '',
  ],
  '247': [
    'ギガインパクト (Giga Impact)',
    'Giga Impact',
    'Gigastoß',
    'Giga Impacto',
    'Giga Impact',
    'Gigaimpatto',
    '',
    '',
  ],
  '248': [
    'スパーキングギガボルト (Sparking Gigavolt)',
    'Gigavolt Havoc',
    'Gigavolt-Funkensalve',
    'Gigavoltio Destructor',
    'Fulguro-Lance Gigavolt',
    'Gigascarica Folgorante',
    '',
    '',
  ],
  '249': [
    'こごえるせかい (Kogoeru Sekai)',
    'Glaciate',
    'Eiszeit',
    'Mundo Gélido',
    'Ère Glaciaire',
    'Gelamondo',
    '',
    '',
  ],
  '250': ['へびにらみ (Hebi Nirami)', 'Glare', 'Giftblick', 'Deslumbrar', 'Regard Médusant', 'Sguardo Feroce', '', ''],
  '251': [
    '(Glitzy Glow)',
    '(Glitzy Glow)',
    '(Glitzy Glow)',
    '(Glitzy Glow)',
    '(Glitzy Glow)',
    '(Glitzy Glow)',
    '(Glitzy Glow)',
    '(Glitzy Glow)',
  ],
  '252': ['くさむすび (Kusa Musubi)', 'Grass Knot', 'Strauchler', 'Hierba Lazo', 'Nœud Herbe', 'Laccioerboso', '', ''],
  '253': [
    'くさのちかい (Kusa no Chikai)',
    'Grass Pledge',
    'Pflanzensäulen',
    'Voto Planta',
    'Aire de Plante',
    'Erbapatto',
    '',
    '',
  ],
  '254': ['くさぶえ (Kusabue)', 'Grass Whistle', 'Grasflöte', 'Silbato', "Siffl'Herbe", 'Meloderba', '', ''],
  '255': [
    'グラスフィールド (Grass Field)',
    'Grassy Terrain',
    'Grasfeld',
    'Campo de Hierba',
    'Champ Herbu',
    'Campo Erboso',
    '',
    '',
  ],
  '256': ['じゅうりょく (Jūryoku)', 'Gravity', 'Erdanziehung', 'Gravedad', 'Gravité', 'Gravità', '', ''],
  '257': ['なきごえ (Nakigoe)', 'Growl', 'Heuler', 'Gruñido', 'Rugissement', 'Ruggito', '', ''],
  '258': ['せいちょう (Seichō)', 'Growth', 'Wachstum', 'Desarrollo', 'Croissance', 'Crescita', '', ''],
  '259': ['おんねん (Onnen)', 'Grudge', 'Nachspiel', 'Rabia', 'Rancune', 'Rancore', '', ''],
  '260': [
    'ガードシェア (Guard Share)',
    'Guard Split',
    'Schutzteiler',
    'Isoguardia',
    'Partage Garde',
    'Paridifesa',
    '',
    '',
  ],
  '261': [
    'ガードスワップ (Guard Swap)',
    'Guard Swap',
    'Schutztausch',
    'Cambia Defensa',
    'Permugarde',
    'Barattoscudo',
    '',
    '',
  ],
  '262': [
    'ガーディアン・デ・アローラ (Guardian de Alola)',
    'Guardian of Alola',
    'Alolas Wächter',
    'Cólera del Guardián',
    "Colère du Gardien d'Alola",
    'Collera del Guardiano',
    '',
    '',
  ],
  '263': [
    'ハサミギロチン (Hasami Guillotine)',
    'Guillotine',
    'Guillotine',
    'Guillotina',
    'Guillotine',
    'Ghigliottina',
    '',
    '',
  ],
  '264': [
    'ダストシュート (Dust Shoot)',
    'Gunk Shot',
    'Mülltreffer',
    'Lanza Mugre',
    'Détricanon',
    'Sporcolancio',
    '',
    '',
  ],
  '265': ['かぜおこし (Kaze Okoshi)', 'Gust', 'Windstoß', 'Tornado', 'Tornade', 'Raffica', '', ''],
  '266': ['ジャイロボール (Gyroball)', 'Gyro Ball', 'Gyroball', 'Giro Bola', 'Gyroballe', 'Vortexpalla', '', ''],
  '267': ['あられ (Arare)', 'Hail', 'Hagelsturm', 'Granizo', 'Grêle', 'Grandine', '', ''],
  '268': ['アームハンマー (Arm Hammer)', 'Hammer Arm', 'Hammerarm', 'Machada', 'Marto-Poing', 'Martelpugno', '', ''],
  '269': ['ハッピータイム (Happy Time)', 'Happy Hour', 'Goldene Zeiten', 'Paga Extra', 'Étrennes', 'Cuccagna', '', ''],
  '270': ['かたくなる (Katakunaru)', 'Harden', 'Härtner', 'Fortaleza', 'Armure', 'Rafforzatore', '', ''],
  '271': ['くろいきり (Kuroi Kiri)', 'Haze', 'Dunkelnebel', 'Niebla', 'Buée Noire', 'Nube', '', ''],
  '272': ['アフロブレイク (Afro Break)', 'Head Charge', 'Steinschädel', 'Ariete', 'Peignée', 'Ricciolata', '', ''],
  '273': [
    'もろはのずつき (Moroha no Zutsuki)',
    'Head Smash',
    'Kopfstoß',
    'Testarazo',
    "Fracass'Tête",
    'Zuccata',
    '',
    '',
  ],
  '274': ['ずつき (Zutsuki)', 'Headbutt', 'Kopfnuss', 'Golpe Cabeza', "Coup d'Boule", 'Bottintesta', '', ''],
  '275': [
    'いやしのすず (Iyashi no Suzu)',
    'Heal Bell',
    'Vitalglocke',
    'Campana Cura',
    'Glas de Soin',
    'Rintoccasana',
    '',
    '',
  ],
  '276': ['かいふくふうじ (Kaifuku Fūji)', 'Heal Block', 'Heilblockade', 'Anticura', 'Anti-Soin', 'Anticura', '', ''],
  '277': [
    'かいふくしれい (Kaifuku Shirei)',
    'Heal Order',
    'Heilbefehl',
    'Auxilio',
    'Appel Soins',
    'Comandocura',
    '',
    '',
  ],
  '278': ['いやしのはどう (Iyashi no Hadō)', 'Heal Pulse', 'Heilwoge', 'Pulso Cura', 'Vibra Soin', 'Ondasana', '', ''],
  '279': [
    'いやしのねがい (Iyashi no Negai)',
    'Healing Wish',
    'Heilopfer',
    'Deseo Cura',
    'Vœu Soin',
    'Curardore',
    '',
    '',
  ],
  '280': ['ハートスタンプ (Heart Stamp)', 'Heart Stamp', 'Herzstempel', 'Arrumaco', 'Crèvecœur', 'Cuorestampo', '', ''],
  '281': [
    'ハートスワップ (Heart Swap)',
    'Heart Swap',
    'Statustausch',
    'Cambia Almas',
    'Permucœur',
    'Cuorbaratto',
    '',
    '',
  ],
  '282': [
    'ヒートスタンプ (Heat Stamp)',
    'Heat Crash',
    'Brandstempel',
    'Golpe Calor',
    'Tacle Feu',
    'Marchiafuoco',
    '',
    '',
  ],
  '283': ['ねっぷう (Neppū)', 'Heat Wave', 'Hitzewelle', 'Onda Ígnea', 'Canicule', 'Ondacalda', '', ''],
  '284': [
    'ヘビーボンバー (Heavy Bomber)',
    'Heavy Slam',
    'Rammboss',
    'Cuerpo Pesado',
    'Tacle Lourd',
    'Pesobomba',
    '',
    '',
  ],
  '285': ['てだすけ (Tedasuke)', 'Helping Hand', 'Rechte Hand', 'Refuerzo', "Coup d'Main", 'Altruismo', '', ''],
  '286': ['たたりめ (Tatarime)', 'Hex', 'Bürde', 'Infortunio', 'Châtiment', 'Sciagura', '', ''],
  '287': [
    'めざめるパワー (Mezameru Power)',
    'Hidden Power',
    'Kraftreserve',
    'Poder Oculto',
    'Puissance Cachée',
    'Introforza',
    '',
    '',
  ],
  '288': [
    '１０まんばりき (Jūman Bariki)',
    'High Horsepower',
    'Pferdestärke',
    'Fuerza Equina',
    'Cavalerie Lourde',
    'Forza Equina',
    '',
    '',
  ],
  '289': [
    'とびひざげり (Tobihizageri)',
    'High Jump Kick',
    'Turmkick',
    'Pat. Salto Alta',
    'Pied Voltige',
    'Calcinvolo',
    '',
    '',
  ],
  '290': ['てかげん (Tekagen)', 'Hold Back', 'Zurückhaltung', 'Clemencia', 'Retenue', 'Riguardo', '', ''],
  '291': [
    'てをつなぐ (Te o Tsunagu)',
    'Hold Hands',
    'Händchenhalten',
    'Manos Juntas',
    'Mains Jointes',
    'Mano nella Mano',
    '',
    '',
  ],
  '292': ['つめとぎ (Tsumetogi)', 'Hone Claws', 'Klauenwetzer', 'Afilagarras', 'Aiguisage', 'Unghiaguzze', '', ''],
  '293': ['つのでつく (Tsuno de Tsuku)', 'Horn Attack', 'Hornattacke', 'Cornada', "Koud'Korne", 'Incornata', '', ''],
  '294': ['つのドリル (Tsuno Drill)', 'Horn Drill', 'Hornbohrer', 'Perforador', "Empal'Korne", 'Perforcorno', '', ''],
  '295': ['ウッドホーン (Wood Horn)', 'Horn Leech', 'Holzgeweih', 'Asta Drenaje', 'Encornebois', 'Legnicorno', '', ''],
  '296': ['とおぼえ (Tōboe)', 'Howl', 'Jauler', 'Aullido', 'Grondement', 'Gridodilotta', '', ''],
  '297': ['ぼうふう (Bōfū)', 'Hurricane', 'Orkan', 'Vendaval', 'Vent Violent', 'Tifone', '', ''],
  '298': [
    'ハイドロカノン (Hydro Cannon)',
    'Hydro Cannon',
    'Aquahaubitze',
    'Hidrocañón',
    'Hydroblast',
    'Idrocannone',
    '',
    '',
  ],
  '299': ['ハイドロポンプ (Hydro Pomp)', 'Hydro Pump', 'Hydropumpe', 'Hidrobomba', 'Hydrocanon', 'Idropompa', '', ''],
  '300': [
    'スーパーアクアトルネード (Super Aqua Tornado)',
    'Hydro Vortex',
    'Super-Wassertornado',
    'Hidrovórtice Abisal',
    'Super Tourbillon Abyssal',
    'Idrovortice Abissale',
    '',
    '',
  ],
  '301': [
    'はかいこうせん (Hakai Kōsen)',
    'Hyper Beam',
    'Hyperstrahl',
    'Hiperrayo',
    'Ultralaser',
    'Iper Raggio',
    '',
    '',
  ],
  '302': [
    'ひっさつまえば (Hissatsu Maeba)',
    'Hyper Fang',
    'Hyperzahn',
    'Hipercolmillo',
    'Croc de Mort',
    'Iperzanna',
    '',
    '',
  ],
  '303': ['ハイパーボイス (Hyper Voice)', 'Hyper Voice', 'Schallwelle', 'Vozarrón', 'Mégaphone', 'Granvoce', '', ''],
  '304': [
    'いじげんラッシュ (Ijigen Rush)',
    'Hyperspace Fury',
    'Dimensionswahn',
    'Cerco Dimensión',
    'Furie Dimension',
    'Urtodimensionale',
    '',
    '',
  ],
  '305': [
    'いじげんホール (Ijigen Hole)',
    'Hyperspace Hole',
    'Dimensionsloch',
    'Paso Dimensional',
    'TrouDimensionnel',
    'Forodimensionale',
    '',
    '',
  ],
  '306': ['さいみんじゅつ (Saimin Jutsu)', 'Hypnosis', 'Hypnose', 'Hipnosis', 'Hypnose', 'Ipnosi', '', ''],
  '307': ['アイスボール (Ice Ball)', 'Ice Ball', 'Frostbeule', 'Bola Hielo', "Ball'Glace", 'Palla Gelo', '', ''],
  '308': ['れいとうビーム (Reitō Beam)', 'Ice Beam', 'Eisstrahl', 'Rayo Hielo', 'Laser Glace', 'Geloraggio', '', ''],
  '309': ['コールドフレア (Cold Flare)', 'Ice Burn', 'Frosthauch', 'Llama Gélida', 'Feu Glacé', 'Vampagelida', '', ''],
  '310': ['こおりのキバ (Koori no Kiba)', 'Ice Fang', 'Eiszahn', 'Colmillo Hielo', 'Crocs Givre', 'Gelodenti', '', ''],
  '311': [
    'アイスハンマー (Ice Hammer)',
    'Ice Hammer',
    'Eishammer',
    'Martillo Hielo',
    'Marteau de Glace',
    'Martelgelo',
    '',
    '',
  ],
  '312': ['れいとうパンチ (Reitō Punch)', 'Ice Punch', 'Eishieb', 'Puño Hielo', 'Poing-Glace', 'Gelopugno', '', ''],
  '313': [
    'こおりのつぶて (Koori no Tsubute)',
    'Ice Shard',
    'Eissplitter',
    'Canto Helado',
    'Éclats Glace',
    'Geloscheggia',
    '',
    '',
  ],
  '314': [
    'つららおとし (Tsurara Otoshi)',
    'Icicle Crash',
    'Eiszapfhagel',
    'Chuzos',
    'Chute Glace',
    'Scagliagelo',
    '',
    '',
  ],
  '315': ['つららばり (Tsurara Bari)', 'Icicle Spear', 'Eisspeer', 'Carámbano', 'Stalagtite', 'Gelolancia', '', ''],
  '316': ['こごえるかぜ (Kogoeru Kaze)', 'Icy Wind', 'Eissturm', 'Viento Hielo', 'Vent Glace', 'Ventogelato', '', ''],
  '317': ['ふういん (Fūin)', 'Imprison', 'Begrenzer', 'Cerca', 'Possessif', 'Esclusiva', '', ''],
  '318': ['やきつくす (Yaki Tsukusu)', 'Incinerate', 'Einäschern', 'Calcinación', 'Calcination', 'Bruciatutto', '', ''],
  '319': ['れんごく (Rengoku)', 'Inferno', 'Inferno', 'Infierno', "Feu d'Enfer", 'Marchiatura', '', ''],
  '320': [
    'ダイナミックフルフレイム (Dynamic Full Flame)',
    'Inferno Overdrive',
    'Dynamische Maxiflamme',
    'Hecatombe Pírica',
    'Pyro-Explosion Cataclysmique',
    'Fiammobomba Detonante',
    '',
    '',
  ],
  '321': ['まとわりつく (Matowaritsuku)', 'Infestation', 'Plage', 'Acoso', 'Harcèlement', 'Assillo', '', ''],
  '322': ['ねをはる (Ne o Haru)', 'Ingrain', 'Verwurzler', 'Arraigo', 'Racines', 'Radicamento', '', ''],
  '323': ['さいはい (Saihai)', 'Instruct', 'Kommando', 'Mandato', 'Sommation', 'Imposizione', '', ''],
  '324': [
    'プラズマシャワー (Plasma Shower)',
    'Ion Deluge',
    'Plasmaschauer',
    'Cortina Plasma',
    'DélugePlasma',
    'Pioggiaplasma',
    '',
    '',
  ],
  '325': ['てっぺき (Teppeki)', 'Iron Defense', 'Eisenabwehr', 'Defensa Férrea', 'Mur de Fer', 'Ferroscudo', '', ''],
  '326': [
    'アイアンヘッド (Iron Head)',
    'Iron Head',
    'Eisenschädel',
    'Cabeza de Hierro',
    'Tête de Fer',
    'Metaltestata',
    '',
    '',
  ],
  '327': [
    'アイアンテール (Iron Tail)',
    'Iron Tail',
    'Eisenschweif',
    'Cola Férrea',
    'Queue de Fer',
    'Codacciaio',
    '',
    '',
  ],
  '328': [
    'さばきのつぶて (Sabaki no Tsubute)',
    'Judgment',
    'Urteilskraft',
    'Sentencia',
    'Jugement',
    'Giudizio',
    '',
    '',
  ],
  '329': ['とびげり (Tobigeri)', 'Jump Kick', 'Sprungkick', 'Patada Salto', 'Pied Sauté', 'Calciosalto', '', ''],
  '330': [
    'からてチョップ (Karate Chop)',
    'Karate Chop',
    'Karateschlag',
    'Golpe Karate',
    'Poing-Karaté',
    'Colpokarate',
    '',
    '',
  ],
  '331': ['スプーンまげ (Spoon Mage)', 'Kinesis', 'Psykraft', 'Kinético', 'Télékinésie', 'Cinèsi', '', ''],
  '332': [
    'キングシールド (King Shield)',
    "King's Shield",
    'Königsschild',
    'Escudo Real',
    'Bouclier Royal',
    'Scudo Reale',
    '',
    '',
  ],
  '333': ['はたきおとす (Hataki Otosu)', 'Knock Off', 'Abschlag', 'Desarme', 'Sabotage', 'Privazione', '', ''],
  '334': [
    'グランドフォース (Ground Force)',
    "Land's Wrath",
    'Bodengewalt',
    'Fuerza Telúrica',
    'Force Chtonienne',
    'Forza Tellurica',
    '',
    '',
  ],
  '335': ['とぎすます (Togisumasu)', 'Laser Focus', 'Konzentration', 'Aguzar', 'Affilage', 'Concentrazione', '', ''],
  '336': ['とっておき (Totteoki)', 'Last Resort', 'Zuflucht', 'Última Baza', 'Dernier Recours', 'Ultimascelta', '', ''],
  '337': ["ふんえん (Fun'en)", 'Lava Plume', 'Flammensturm', 'Humareda', 'Ébullilave', 'Lavasbuffo', '', ''],
  '338': [
    'リーフブレード (Leaf Blade)',
    'Leaf Blade',
    'Laubklinge',
    'Hoja Aguda',
    'Lame-Feuille',
    'Fendifoglia',
    '',
    '',
  ],
  '339': [
    'リーフストーム (Leaf Storm)',
    'Leaf Storm',
    'Blättersturm',
    'Lluevahojas',
    'Tempête Verte',
    'Verdebufera',
    '',
    '',
  ],
  '340': [
    'グラスミキサー (Grass Mixer)',
    'Leaf Tornado',
    'Grasmixer',
    'Ciclón de Hojas',
    'Phytomixeur',
    'Vorticerba',
    '',
    '',
  ],
  '341': ['このは (Ko no Ha)', 'Leafage', 'Blattwerk', 'Follaje', 'Feuillage', 'Fogliame', '', ''],
  '342': ['きゅうけつ (Kyūketsu)', 'Leech Life', 'Blutsauger', 'Chupavidas', 'Vampirisme', 'Sanguisuga', '', ''],
  '343': [
    'やどりぎのタネ (Yadorigi no Tane)',
    'Leech Seed',
    'Egelsamen',
    'Drenadoras',
    'Vampigraine',
    'Parassiseme',
    '',
    '',
  ],
  '344': ['にらみつける (Niramitsukeru)', 'Leer', 'Silberblick', 'Malicioso', "Groz'Yeux", 'Fulmisguardo', '', ''],
  '345': [
    'ぽかぼかフレンドタイム (Poka-Boka Friend Time)',
    "Let's Snuggle Forever",
    'Herzliche Knuddelkloppe',
    'Somanta Amistosa',
    'Patati-Patattrape',
    'Dolcesacco di Botte',
    '',
    '',
  ],
  '346': ['したでなめる (Shita de Nameru)', 'Lick', 'Schlecker', 'Lengüetazo', 'Léchouille', 'Leccata', '', ''],
  '347': [
    'はめつのひかり (Hametsu no Hikari)',
    'Light of Ruin',
    'Lux Calamitatis',
    'Luz Aniquiladora',
    'Lumière du Néant',
    'Luce Nefasta',
    '',
    '',
  ],
  '348': [
    'ひかりのかべ (Hikari no Kabe)',
    'Light Screen',
    'Lichtschild',
    'Pantalla Luz',
    'Mur Lumière',
    'Schermoluce',
    '',
    '',
  ],
  '349': [
    '天焦がす滅亡の光 (Ten Kogasu Metsubō no Hikari)',
    'Light That Burns the Sky',
    'Licht des Erlöschens',
    'Fotodestrucción Apocalíptica',
    'Apocalypsis Luminis',
    'Fotodistruzione Apocalittica',
    '',
    '',
  ],
  '350': [
    'アクアブレイク (Aqua Break)',
    'Liquidation',
    'Aquadurchstoß',
    'Hidroariete',
    'Aqua-Brèche',
    'Idrobreccia',
    '',
    '',
  ],
  '351': ['ロックオン (Lock On)', 'Lock-On', 'Zielschuss', 'Fijar Blanco', 'Verrouillage', 'Localizza', '', ''],
  '352': [
    'あくまのキッス (Akuma no Kiss)',
    'Lovely Kiss',
    'Todeskuss',
    'Beso Amoroso',
    'Grobisou',
    'Demonbacio',
    '',
    '',
  ],
  '353': ['けたぐり (Ketaguri)', 'Low Kick', 'Fußkick', 'Patada Baja', 'Balayage', 'Colpo Basso', '', ''],
  '354': ['ローキック (Low Kick)', 'Low Sweep', 'Fußtritt', 'Puntapié', 'Balayette', 'Calciobasso', '', ''],
  '355': ['おまじない (Omajinai)', 'Lucky Chant', 'Beschwörung', 'Conjuro', 'Air Veinard', 'Fortuncanto', '', ''],
  '356': [
    'みかづきのまい (Mikazuki no Mai)',
    'Lunar Dance',
    'Lunartanz',
    'Danza Lunar',
    'Danse-Lune',
    'Lunardanza',
    '',
    '',
  ],
  '357': ['とびかかる (Tobikakaru)', 'Lunge', 'Anfallen', 'Plancha', 'Furie-Bond', 'Assalto', '', ''],
  '358': [
    'ラスターパージ (Luster Purge)',
    'Luster Purge',
    'Scheinwerfer',
    'Resplandor',
    'Lumi-Éclat',
    'Abbagliante',
    '',
    '',
  ],
  '359': ['マッハパンチ (Mach Punch)', 'Mach Punch', 'Tempohieb', 'Ultrapuño', 'Mach Punch', 'Pugnorapido', '', ''],
  '360': [
    'マジックコート (Magic Coat)',
    'Magic Coat',
    'Magiemantel',
    'Capa Mágica',
    'Reflet Magik',
    'Magivelo',
    '',
    '',
  ],
  '361': [
    'マジックルーム (Magic Room)',
    'Magic Room',
    'Magieraum',
    'Zona Mágica',
    'Zone Magique',
    'Magicozona',
    '',
    '',
  ],
  '362': [
    'マジカルリーフ (Magical Leaf)',
    'Magical Leaf',
    'Zauberblatt',
    'Hoja Mágica',
    'Feuillemagik',
    'Fogliamagica',
    '',
    '',
  ],
  '363': [
    'マグマストーム (Magma Storm)',
    'Magma Storm',
    'Lavasturm',
    'Lluvia Ígnea',
    'Vortex Magma',
    'Magmaclisma',
    '',
    '',
  ],
  '364': [
    'マグネットボム (Magnet Bomb)',
    'Magnet Bomb',
    'Magnetbombe',
    'Bomba Imán',
    'Bombaimant',
    'Bombagnete',
    '',
    '',
  ],
  '365': ['でんじふゆう (Denji Fuyū)', 'Magnet Rise', 'Magnetflug', 'Levitón', 'Vol Magnétik', 'Magnetascesa', '', ''],
  '366': [
    'じばそうさ (Jiba Sōsa)',
    'Magnetic Flux',
    'Magnetregler',
    'Aura Magnética',
    'Magné-Contrôle',
    'Controllo Polare',
    '',
    '',
  ],
  '367': ['マグニチュード (Magnitude)', 'Magnitude', 'Intensität', 'Magnitud', 'Ampleur', 'Magnitudo', '', ''],
  '368': [
    'ハイパーダーククラッシャー (Hyper Dark Crusher)',
    'Malicious Moonsault',
    'Hyper Dark Crusher',
    'Hiperplancha Oscura',
    'Dark Body Press',
    'Iperschianto delle Tenebre',
    '',
    '',
  ],
  '369': [
    'たたみがえし (Tatami-gaeshi)',
    'Mat Block',
    'Tatami-Schild',
    'Escudo Tatami',
    'Tatamigaeshi',
    'Ribaltappeto',
    '',
    '',
  ],
  '370': ['さきどり (Sakidori)', 'Me First', 'Egotrip', 'Yo Primero', "Moi d'Abord", 'Precedenza', '', ''],
  '371': [
    'くろいまなざし (Kuroi Manazashi)',
    'Mean Look',
    'Horrorblick',
    'Mal De Ojo',
    'Regard Noir',
    'Malosguardo',
    '',
    '',
  ],
  '372': ['ヨガのポーズ (Yoga no Pose)', 'Meditate', 'Meditation', 'Meditación', 'Yoga', 'Meditazione', '', ''],
  '373': [
    'メガドレイン (Mega Drain)',
    'Mega Drain',
    'Megasauger',
    'Megaagotar',
    'Méga-Sangsue',
    'Megassorbimento',
    '',
    '',
  ],
  '374': ['メガトンキック (Megaton Kick)', 'Mega Kick', 'Megakick', 'Megapatada', 'Ultimawashi', 'Megacalcio', '', ''],
  '375': ['メガトンパンチ (Megaton Punch)', 'Mega Punch', 'Megahieb', 'Megapuño', 'Ultimapoing', 'Megapugno', '', ''],
  '376': ['メガホーン (Megahorn)', 'Megahorn', 'Vielender', 'Megacuerno', 'Mégacorne', 'Megacorno', '', ''],
  '377': ['おきみやげ (Okimiyage)', 'Memento', 'Memento-Mori', 'Legado', 'Souvenir', 'Memento', '', ''],
  '378': [
    'ムーンライトブラスター (Moonlight Blaster)',
    'Menacing Moonraze Maelstrom',
    'Geballter Mondlaser',
    'Deflagración Lunar',
    'Rayons Séléno-Explosifs',
    'Deflagrazione Lunare',
    '',
    '',
  ],
  '379': [
    'メタルバースト (Metal Burst)',
    'Metal Burst',
    'Metallstoß',
    'Represión Metal',
    'Fulmifer',
    'Metalscoppio',
    '',
    '',
  ],
  '380': [
    'メタルクロー (Metal Claw)',
    'Metal Claw',
    'Metallklaue',
    'Garra Metal',
    'Griffe Acier',
    'Ferrartigli',
    '',
    '',
  ],
  '381': [
    'きんぞくおん (Kinzoku On)',
    'Metal Sound',
    'Metallsound',
    'Eco Metálico',
    'Strido-Son',
    'Ferrostrido',
    '',
    '',
  ],
  '382': [
    'コメットパンチ (Comet Punch)',
    'Meteor Mash',
    'Sternenhieb',
    'Puño Meteoro',
    'Poing Météor',
    'Meteorpugno',
    '',
    '',
  ],
  '383': ['ゆびをふる (Yubi o Furu)', 'Metronome', 'Metronom', 'Metrónomo', 'Métronome', 'Metronomo', '', ''],
  '384': ['ミルクのみ (Milk Nomi)', 'Milk Drink', 'Milchgetränk', 'Batido', 'Lait à Boire', 'Buonlatte', '', ''],
  '385': ['ものまね (Monomane)', 'Mimic', 'Mimikry', 'Mimético', 'Copie', 'Mimica', '', ''],
  '386': [
    'ビックリヘッド (Bikkuri Head)',
    'Mind Blown',
    'Knallkopf',
    'Cabeza Sorpresa',
    'Caboche-Kaboum',
    'Sbalorditesta',
    '',
    '',
  ],
  '387': ['こころのめ (Kokoro no Me)', 'Mind Reader', 'Willensleser', 'Telépata', 'Lire-Esprit', 'Leggimente', '', ''],
  '388': ['ちいさくなる (Chīsakunaru)', 'Minimize', 'Komprimator', 'Reducción', 'Lilliput', 'Minimizzato', '', ''],
  '389': ['ミラクルアイ (Miracle Eye)', 'Miracle Eye', 'Wunderauge', 'Gran Ojo', 'Œil Miracle', 'Miracolvista', '', ''],
  '390': [
    'ミラーコート (Mirror Coat)',
    'Mirror Coat',
    'Spiegelcape',
    'Manto Espejo',
    'Voile Miroir',
    'Specchiovelo',
    '',
    '',
  ],
  '391': ['オウムがえし (Ōmu Gaeshi)', 'Mirror Move', 'Spiegeltrick', 'Mov. Espejo', 'Mimique', 'Speculmossa', '', ''],
  '392': [
    'ミラーショット (Mirror Shot)',
    'Mirror Shot',
    'Spiegelsalve',
    'Disparo Espejo',
    'Miroi-Tir',
    'Cristalcolpo',
    '',
    '',
  ],
  '393': ['しろいきり (Shiroi Kiri)', 'Mist', 'Weißnebel', 'Neblina', 'Brume', 'Nebbia', '', ''],
  '394': ['ミストボール (Mist Ball)', 'Mist Ball', 'Nebelball', 'Bola Neblina', "Ball'Brume", 'Foschisfera', '', ''],
  '395': [
    'ミストフィールド (Mist Field)',
    'Misty Terrain',
    'Nebelfeld',
    'Campo de Niebla',
    'Champ Brumeux',
    'Campo Nebbioso',
    '',
    '',
  ],
  '396': [
    'ムーンフォース (Moon Force)',
    'Moonblast',
    'Mondgewalt',
    'Fuerza Lunar',
    'Pouvoir Lunaire',
    'Forza Lunare',
    '',
    '',
  ],
  '397': [
    'シャドーレイ (Shadow Ray)',
    'Moongeist Beam',
    'Schattenstrahl',
    'Rayo Umbrío',
    'Rayon Spectral',
    "Raggio d'Ombra",
    '',
    '',
  ],
  '398': ['つきのひかり (Tsuki no Hikari)', 'Moonlight', 'Mondschein', 'Luz Lunar', 'Rayon Lune', 'Lucelunare', '', ''],
  '399': [
    'あさのひざし (Asa no Hizashi)',
    'Morning Sun',
    'Morgengrauen',
    'Sol Matinal',
    'Aurore',
    'Mattindoro',
    '',
    '',
  ],
  '400': [
    'どろばくだん (Doro Bakudan)',
    'Mud Bomb',
    'Schlammbombe',
    'Bomba Fango',
    'Boue-Bombe',
    'Pantanobomba',
    '',
    '',
  ],
  '401': ['マッドショット (Mud Shot)', 'Mud Shot', 'Lehmschuss', 'Disparo Lodo', 'Tir de Boue', 'Colpodifango', '', ''],
  '402': ['どろあそび (Doro Asobi)', 'Mud Sport', 'Lehmsuhler', 'Chapoteo Lodo', 'Lance-Boue', 'Fangata', '', ''],
  '403': ['どろかけ (Dorokake)', 'Mud-Slap', 'Lehmschelle', 'Bofetón Lodo', "Coud'Boue", 'Fangosberla', '', ''],
  '404': ['だくりゅう (Dakuryū)', 'Muddy Water', 'Lehmbrühe', 'Agua Lodosa', 'Ocroupi', 'Fanghiglia', '', ''],
  '405': [
    'マルチアタック (Multi-Attack)',
    'Multi-Attack',
    'Multi-Angriff',
    'Multiataque',
    'Coup Varia-Type',
    'Multiattacco',
    '',
    '',
  ],
  '406': [
    'マジカルフレイム (Magical Flame)',
    'Mystical Fire',
    'Magieflamme',
    'Llama Embrujada',
    'Feu Ensorcelé',
    'Magifiamma',
    '',
    '',
  ],
  '407': ['わるだくみ (Waru Dakumi)', 'Nasty Plot', 'Ränkeschmied', 'Maquinación', 'Machination', 'Congiura', '', ''],
  '408': [
    'しぜんのめぐみ (Shizen no Megumi)',
    'Natural Gift',
    'Beerenkräfte',
    'Don Natural',
    'Don Naturel',
    'Dononaturale',
    '',
    '',
  ],
  '409': [
    'しぜんのちから (Shizen no Chikara)',
    'Nature Power',
    'Natur-Kraft',
    'Adaptación',
    'Force-Nature',
    'Naturforza',
    '',
    '',
  ],
  '410': [
    'しぜんのいかり (Shizen no Ikari)',
    "Nature's Madness",
    'Naturzorn',
    'Furia Natural',
    'Ire de la Nature',
    'Ira della Natura',
    '',
    '',
  ],
  '411': [
    'ニードルアーム (Needle Arm)',
    'Needle Arm',
    'Nietenranke',
    'Brazo Pincho',
    'Poing Dard',
    'Pugnospine',
    '',
    '',
  ],
  '412': [
    "無限暗夜への誘い (Mugen An'ya e no Izanai)",
    'Never-Ending Nightmare',
    'Ewige Nacht',
    'Presa Espectral',
    'Appel des Ombres Éternelles',
    'Abbraccio Spettrale',
    '',
    '',
  ],
  '413': ['ナイトバースト (Night Burst)', 'Night Daze', 'Nachtflut', 'Pulso Noche', 'Explonuit', 'Urtoscuro', '', ''],
  '414': [
    'ナイトヘッド (Night Head)',
    'Night Shade',
    'Nachtnebel',
    'Tinieblas',
    'Ombre Nocturne',
    'Ombra Notturna',
    '',
    '',
  ],
  '415': ['つじぎり (Tsujigiri)', 'Night Slash', 'Nachthieb', 'Tajo Umbrío', 'Tranche-Nuit', 'Nottesferza', '', ''],
  '416': ['あくむ (Akumu)', 'Nightmare', 'Nachtmahr', 'Pesadilla', 'Cauchemar', 'Incubo', '', ''],
  '417': ['おたけび (Otakebi)', 'Noble Roar', 'Kampfgebrüll', 'Rugido de Guerra', 'Râle Mâle', 'Urlo', '', ''],
  '418': [
    'ほっぺすりすり (Hoppe Suri Suri)',
    'Nuzzle',
    'Wangenrubbler',
    'Moflete Estático',
    'Frotte-Frimousse',
    'Elettrococcola',
    '',
    '',
  ],
  '419': [
    'デスウイング (Death Wing)',
    'Oblivion Wing',
    'Unheilsschwingen',
    'Ala Mortífera',
    'Mort-Ailes',
    'Ali del Fato',
    '',
    '',
  ],
  '420': [
    'わだつみのシンフォニア (Wadatsumi no Symphonia)',
    'Oceanic Operetta',
    'Grandiose Meeressymphonie',
    'Sinfonía de la Diva Marina',
    'Symphonie des Ondines',
    'Sinfonia del Mare',
    '',
    '',
  ],
  '421': ['オクタンほう (Okutank Hō)', 'Octazooka', 'Octazooka', 'Pulpocañón', 'Octazooka', 'Octazooka', '', ''],
  '422': ['かぎわける (Kagiwakeru)', 'Odor Sleuth', 'Schnüffler', 'Rastreo', 'Flair', 'Segugio', '', ''],
  '423': [
    'あやしいかぜ (Ayashii Kaze)',
    'Ominous Wind',
    'Unheilböen',
    'Viento Aciago',
    'Vent Mauvais',
    'Funestovento',
    '',
    '',
  ],
  '424': [
    'こんげんのはどう (Kongen no Hadō)',
    'Origin Pulse',
    'Ursprungswoge',
    'Pulso Primigenio',
    'Onde Originelle',
    'Primopulsar',
    '',
    '',
  ],
  '425': ['げきりん (Gekirin)', 'Outrage', 'Wutanfall', 'Enfado', 'Colère', 'Oltraggio', '', ''],
  '426': ['オーバーヒート (Overheat)', 'Overheat', 'Hitzekoller', 'Sofoco', 'Surchauffe', 'Vampata', '', ''],
  '427': ['いたみわけ (Itamiwake)', 'Pain Split', 'Leidteiler', 'Divide Dolor', 'Balance', 'Malcomune', '', ''],
  '428': [
    'パラボラチャージ (Parabola Charge)',
    'Parabolic Charge',
    'Parabolladung',
    'Carga Parábola',
    'Parabocharge',
    'Caricaparabola',
    '',
    '',
  ],
  '429': [
    'すてゼリフ (Sute Zerifu)',
    'Parting Shot',
    'Abgangstirade',
    'Última Palabra',
    'Dernier Mot',
    'Monito',
    '',
    '',
  ],
  '430': ['ネコにこばん (Neko ni Koban)', 'Pay Day', 'Zahltag', 'Día de Pago', 'Jackpot', 'Giornopaga', '', ''],
  '431': ['しっぺがえし (Shippegaeshi)', 'Payback', 'Gegenstoß', 'Vendetta', 'Représailles', 'Rivincita', '', ''],
  '432': ['つつく (Tsutsuku)', 'Peck', 'Schnabel', 'Picotazo', 'Picpic', 'Beccata', '', ''],
  '433': ['ほろびのうた (Horobi no Uta)', 'Perish Song', 'Abgesang', 'Canto Mortal', 'Requiem', 'Ultimocanto', '', ''],
  '434': [
    'はなふぶき (Hana Fubuki)',
    'Petal Blizzard',
    'Blütenwirbel',
    'Tormenta Floral',
    'Tempête Florale',
    'Fiortempesta',
    '',
    '',
  ],
  '435': [
    'はなびらのまい (Hanabira no Mai)',
    'Petal Dance',
    'Blättertanz',
    'Danza Pétalo',
    'Danse-Fleur',
    'Petalodanza',
    '',
    '',
  ],
  '436': [
    'ゴーストダイブ (Ghost Dive)',
    'Phantom Force',
    'Phantomkraft',
    'Golpe Fantasma',
    'Hantise',
    'Spettrotuffo',
    '',
    '',
  ],
  '437': [
    'フォトンゲイザー (Photon Geyser)',
    'Photon Geyser',
    'Photonen-Geysir',
    'Géiser Fotónico',
    'Photo-Geyser',
    'Geyser Fotonico',
    '',
    '',
  ],
  '438': [
    '(Pika Papow)',
    '(Pika Papow)',
    '(Pika Papow)',
    '(Pika Papow)',
    '(Pika Papow)',
    '(Pika Papow)',
    '(Pika Papow)',
    '(Pika Papow)',
  ],
  '439': [
    'ミサイルばり (Missile Bari)',
    'Pin Missile',
    'Nadelrakete',
    'Pin Misil',
    'Dard-Nuée',
    'Missilspillo',
    '',
    '',
  ],
  '440': [
    'プラズマフィスト (Plasma Fist)',
    'Plasma Fists',
    'Plasmafäuste',
    'Puños Plasma',
    'Plasma Punch',
    'Pugni Plasma',
    '',
    '',
  ],
  '441': [
    'なかよくする (Nakayoku-suru)',
    'Play Nice',
    'Kameradschaft',
    'Camaradería',
    'Camaraderie',
    'Simpatia',
    '',
    '',
  ],
  '442': ['じゃれつく (Jaretsuku)', 'Play Rough', 'Knuddler', 'Carantoña', 'Câlinerie', 'Carineria', '', ''],
  '443': ['ついばむ (Tsuibamu)', 'Pluck', 'Pflücker', 'Picoteo', 'Picore', 'Spennata', '', ''],
  '444': [
    'どくどくのキバ (Dokudoku no Kiba)',
    'Poison Fang',
    'Giftzahn',
    'Colmillo Ven',
    'Crochet Venin',
    'Velenodenti',
    '',
    '',
  ],
  '445': ['どくガス (Doku Gas)', 'Poison Gas', 'Giftwolke', 'Gas Venenoso', 'Gaz Toxik', 'Velenogas', '', ''],
  '446': ['どくづき (Dokudzuki)', 'Poison Jab', 'Gifthieb', 'Puya Nociva', 'Direct Toxik', 'Velenpuntura', '', ''],
  '447': [
    'どくのこな (Doku no Kona)',
    'Poison Powder',
    'Giftpuder',
    'Polvo Veneno',
    'Poudre Toxik',
    'Velenpolvere',
    '',
    '',
  ],
  '448': ['どくばり (Doku Bari)', 'Poison Sting', 'Giftstachel', 'Picotazo Ven', 'Dard-Venin', 'Velenospina', '', ''],
  '449': [
    'ポイズンテール (Poison Tail)',
    'Poison Tail',
    'Giftschweif',
    'Cola Veneno',
    'Queue-Poison',
    'Velenocoda',
    '',
    '',
  ],
  '450': [
    'かふんだんご (Kahun Dango)',
    'Pollen Puff',
    'Pollenknödel',
    'Bola de Polen',
    'Boule Pollen',
    'Sferapolline',
    '',
    '',
  ],
  '451': ['はたく (Hataku)', 'Pound', 'Pfund', 'Destructor', "Écras'Face", 'Botta', '', ''],
  '452': [
    'ふんじん (Funjin)',
    'Powder',
    'Pulverschleuder',
    'Polvo Explosivo',
    'Nuée de Poudre',
    'Pulviscoppio',
    '',
    '',
  ],
  '453': ['こなゆき (Konayuki)', 'Powder Snow', 'Pulverschnee', 'Nieve Polvo', 'Poudreuse', 'Polneve', '', ''],
  '454': ['パワージェム (Power Gem)', 'Power Gem', 'Juwelenkraft', 'Joya de Luz', 'Rayon Gemme', 'Gemmoforza', '', ''],
  '455': [
    'パワーシェア (Power Share)',
    'Power Split',
    'Kraftteiler',
    'Isofuerza',
    'Partage Force',
    'Pariattacco',
    '',
    '',
  ],
  '456': [
    'パワースワップ (Power Swap)',
    'Power Swap',
    'Krafttausch',
    'Cambia Fuerza',
    'Permuforce',
    'Barattoforza',
    '',
    '',
  ],
  '457': [
    'パワートリック (Power Trick)',
    'Power Trick',
    'Krafttrick',
    'Truco Fuerza',
    'Astuce Force',
    'Ingannoforza',
    '',
    '',
  ],
  '458': ['つけあがる (Tsukeagaru)', 'Power Trip', 'Überheblichkeit', 'Chulería', 'Arrogance', 'Tracotanza', '', ''],
  '459': ['パワーウィップ (Power Whip)', 'Power Whip', 'Blattgeißel', 'Latigazo', 'Mégafouet', 'Vigorcolpo', '', ''],
  '460': [
    'グロウパンチ (Grow Punch)',
    'Power-Up Punch',
    'Steigerungshieb',
    'Puño Incremento',
    'Poing Boost',
    'Crescipugno',
    '',
    '',
  ],
  '461': [
    'だんがいのつるぎ (Dangai no Tsurugi)',
    'Precipice Blades',
    'Abgrundsklinge',
    'Filo del Abismo',
    'Lame Pangéenne',
    'Spade Telluriche',
    '',
    '',
  ],
  '462': ['プレゼント (Present)', 'Present', 'Geschenk', 'Presente', 'Cadeau', 'Regalino', '', ''],
  '463': [
    'プリズムレーザー (Prism Laser)',
    'Prismatic Laser',
    'Prisma-Laser',
    'Láser Prisma',
    'Laser Prisme',
    'Prismalaser',
    '',
    '',
  ],
  '464': ['まもる (Mamoru)', 'Protect', 'Schutzschild', 'Protección', 'Abri', 'Protezione', '', ''],
  '465': ['サイケこうせん (Psych Kōsen)', 'Psybeam', 'Psystrahl', 'Psicorrayo', 'Rafale Psy', 'Psicoraggio', '', ''],
  '466': ['じこあんじ (Jikoanji)', 'Psych Up', 'Psycho-Plus', 'Más Psique', 'Boost', 'Psicamisù', '', ''],
  '467': ['サイコキネシス (Psychokinesis)', 'Psychic', 'Psychokinese', 'Psíquico', 'Psyko', 'Psichico', '', ''],
  '468': [
    'サイコファング (Psycho Fang)',
    'Psychic Fangs',
    'Psychobeißer',
    'Psicocolmillo',
    'Psycho-Croc',
    'Psicozanna',
    '',
    '',
  ],
  '469': [
    'サイコフィールド (Psycho Field)',
    'Psychic Terrain',
    'Psychofeld',
    'Campo Psíquico',
    'Champ Psychique',
    'Campo Psichico',
    '',
    '',
  ],
  '470': [
    'サイコブースト (Psycho Boost)',
    'Psycho Boost',
    'Psyschub',
    'Psicoataque',
    'Psycho Boost',
    'Psicoslancio',
    '',
    '',
  ],
  '471': [
    'サイコカッター (Psycho Cutter)',
    'Psycho Cut',
    'Psychoklinge',
    'Psicocorte',
    'Coupe Psycho',
    'Psicotaglio',
    '',
    '',
  ],
  '472': [
    'サイコシフト (Psycho Shift)',
    'Psycho Shift',
    'Psybann',
    'Psicocambio',
    'Échange Psy',
    'Psicotrasfer',
    '',
    '',
  ],
  '473': ['サイコショック (Psycho Shock)', 'Psyshock', 'Psychoschock', 'Psicocarga', 'Choc Psy', 'Psicoshock', '', ''],
  '474': [
    'サイコブレイク (Psycho Break)',
    'Psystrike',
    'Psychostoß',
    'Onda Mental',
    'Frappe Psy',
    'Psicobotta',
    '',
    '',
  ],
  '475': ['サイコウェーブ (Psycho Wave)', 'Psywave', 'Psywelle', 'Psicoonda', 'Vague Psy', 'Psiconda', '', ''],
  '476': [
    'ほんきをだすこうげき (Honki o Dasu Kōgeki)',
    'Pulverizing Pancake',
    'Schluss mit lustig',
    'Arrojo Intempestivo',
    'Gare au Ronflex',
    'Adesso Faccio sul Serio',
    '',
    '',
  ],
  '477': ['おしおき (Oshioki)', 'Punishment', 'Strafattacke', 'Castigo', 'Punition', 'Punizione', '', ''],
  '478': ['じょうか (Jōka)', 'Purify', 'Läuterung', 'Purificación', 'Purification', 'Purificazione', '', ''],
  '479': ['おいうち (Oiuchi)', 'Pursuit', 'Verfolgung', 'Persecución', 'Poursuite', 'Inseguimento', '', ''],
  '480': ['さきおくり (Saki Okuri)', 'Quash', 'Verzögerung', 'Último Lugar', 'À la Queue', 'Spintone', '', ''],
  '481': [
    'でんこうせっか (Denkō Sekka)',
    'Quick Attack',
    'Ruckzuckhieb',
    'Ataque Rápido',
    'Vive-attaque',
    'Attacco Rapido',
    '',
    '',
  ],
  '482': ['ファストガード (Fast Guard)', 'Quick Guard', 'Rapidschutz', 'Anticipo', 'Prévention', 'Anticipo', '', ''],
  '483': [
    'ちょうのまい (Chō no Mai)',
    'Quiver Dance',
    'Falterreigen',
    'Danza Aleteo',
    'Papillodanse',
    'Eledanza',
    '',
    '',
  ],
  '484': ['いかり (Ikari)', 'Rage', 'Raserei', 'Furia', 'Frénésie', 'Ira', '', ''],
  '485': [
    'いかりのこな (Ikari no Kona)',
    'Rage Powder',
    'Wutpulver',
    'Polvo Ira',
    'Poudre Fureur',
    'Polverabbia',
    '',
    '',
  ],
  '486': ['あまごい (Amagoi)', 'Rain Dance', 'Regentanz', 'Danza Lluvia', 'Danse Pluie', 'Pioggiadanza', '', ''],
  '487': [
    'こうそくスピン (Kōsoku Spin)',
    'Rapid Spin',
    'Turbodreher',
    'Giro Rápido',
    'Tour Rapide',
    'Rapigiro',
    '',
    '',
  ],
  '488': [
    'はっぱカッター (Happa Cutter)',
    'Razor Leaf',
    'Rasierblatt',
    'Hoja Afilada',
    "Tranch'Herbe",
    'Foglielama',
    '',
    '',
  ],
  '489': [
    'シェルブレード (Shell Blade)',
    'Razor Shell',
    'Kalkklinge',
    'Concha Filo',
    'Coquilame',
    'Conchilama',
    '',
    '',
  ],
  '490': [
    'かまいたち (Kamaitachi)',
    'Razor Wind',
    'Klingensturm',
    'Viento Cortante',
    'Coupe-Vent',
    'Ventagliente',
    '',
    '',
  ],
  '491': ['じこさいせい (Jikosaisei)', 'Recover', 'Genesung', 'Recuperación', 'Soin', 'Ripresa', '', ''],
  '492': ['リサイクル (Recycle)', 'Recycle', 'Aufbereitung', 'Reciclaje', 'Recyclage', 'Riciclo', '', ''],
  '493': ['リフレクター (Reflector)', 'Reflect', 'Reflektor', 'Reflejo', 'Protection', 'Riflesso', '', ''],
  '494': [
    'ミラータイプ (Mirror Type)',
    'Reflect Type',
    'Typenspiegel',
    'Clonatipo',
    'Copie Type',
    'Riflettipo',
    '',
    '',
  ],
  '495': ['リフレッシュ (Refresh)', 'Refresh', 'Heilung', 'Alivio', 'Régénération', 'Rinfrescata', '', ''],
  '496': [
    'いにしえのうた (Inishie no Uta)',
    'Relic Song',
    'Urgesang',
    'Canto Arcaico',
    'Chant Antique',
    'Cantoantico',
    '',
    '',
  ],
  '497': ['ねむる (Nemuru)', 'Rest', 'Erholung', 'Descanso', 'Repos', 'Riposo', '', ''],
  '498': ['かたきうち (Katakiuchi)', 'Retaliate', 'Heimzahlung', 'Represalia', 'Vengeance', 'Nemesi', '', ''],
  '499': ['おんがえし (Ongaeshi)', 'Return', 'Rückkehr', 'Retribución', 'Retour', 'Ritorno', '', ''],
  '500': [
    'めざめるダンス (Mezameru Dance)',
    'Revelation Dance',
    'Wecktanz',
    'Danza Despertar',
    'Danse Éveil',
    'Mutadanza',
    '',
    '',
  ],
  '501': ['リベンジ (Revenge)', 'Revenge', 'Vergeltung', 'Desquite', 'Vendetta', 'Vendetta', '', ''],
  '502': ['きしかいせい (Kishi Kaisei)', 'Reversal', 'Gegenschlag', 'Inversión', 'Contre', 'Contropiede', '', ''],
  '503': ['ほえる (Hoeru)', 'Roar', 'Brüller', 'Rugido', 'Hurlement', 'Boato', '', ''],
  '504': [
    'ときのほうこう (Toki no Hōkō)',
    'Roar of Time',
    'Zeitenlärm',
    'Distorsión',
    'Hurle-Temps',
    'Fragortempo',
    '',
    '',
  ],
  '505': ['ロックブラスト (Rock Blast)', 'Rock Blast', 'Felswurf', 'Pedrada', 'Boule Roc', 'Cadutamassi', '', ''],
  '506': ['ロッククライム (Rock Climb)', 'Rock Climb', 'Kraxler', 'Treparrocas', 'Escalade', 'Scalaroccia', '', ''],
  '507': ['ロックカット (Rock Cut)', 'Rock Polish', 'Steinpolitur', 'Pulimento', 'Poliroche', 'Lucidatura', '', ''],
  '508': ['いわなだれ (Iwa Nadare)', 'Rock Slide', 'Steinhagel', 'Avalancha', 'Éboulement', 'Frana', '', ''],
  '509': ['いわくだき (Iwakudaki)', 'Rock Smash', 'Zertrümmerer', 'Golpe Roca', 'Éclate-Roc', 'Spaccaroccia', '', ''],
  '510': ['いわおとし (Iwa Otoshi)', 'Rock Throw', 'Steinwurf', 'Lanzarrocas', 'Jet-Pierres', 'Sassata', '', ''],
  '511': ['がんせきふうじ (Ganseki Fūji)', 'Rock Tomb', 'Felsgrab', 'Tumba Rocas', 'Tomberoche', 'Rocciotomba', '', ''],
  '512': [
    'がんせきほう (Ganseki Hō)',
    'Rock Wrecker',
    'Felswerfer',
    'Romperrocas',
    'Roc-Boulet',
    'Devastomasso',
    '',
    '',
  ],
  '513': ['なりきり (Narikiri)', 'Role Play', 'Rollentausch', 'Imitación', 'Imitation', 'Giocodiruolo', '', ''],
  '514': ['まわしげり (Mawashigeri)', 'Rolling Kick', 'Fegekick', 'Patada Giro', 'Mawashi Geri', 'Calciorullo', '', ''],
  '515': ['ころがる (Korogaru)', 'Rollout', 'Walzer', 'Desenrollar', 'Roulade', 'Rotolamento', '', ''],
  '516': ['はねやすめ (Hane Yasume)', 'Roost', 'Ruheort', 'Respiro', 'Atterrissage', 'Trespolo', '', ''],
  '517': ['たがやす (Tagayasu)', 'Rototiller', 'Pflüger', 'Fertilizante', 'Fertilisation', 'Aracampo', '', ''],
  '518': ['りんしょう (Rinshō)', 'Round', 'Kanon', 'Canon', 'Chant Canon', 'Coro', '', ''],
  '519': [
    'せいなるほのお (Seinaru Honō)',
    'Sacred Fire',
    'Läuterfeuer',
    'Fuego Sagrado',
    'Feu Sacré',
    'Magifuoco',
    '',
    '',
  ],
  '520': [
    'せいなるつるぎ (Seinaru Tsurugi)',
    'Sacred Sword',
    'Sanctoklinge',
    'Espada Santa',
    'Lame Sainte',
    'Spadasolenne',
    '',
    '',
  ],
  '521': [
    'しんぴのまもり (Shinpi no Mamori)',
    'Safeguard',
    'Bodyguard',
    'Velo Sagrado',
    'Rune Protect',
    'Salvaguardia',
    '',
    '',
  ],
  '522': ['すなかけ (Sunakake)', 'Sand Attack', 'Sandwirbel', 'Ataque Arena', 'Jet de Sable', 'Turbosabbia', '', ''],
  '523': ['すなじごく (Suna Jigoku)', 'Sand Tomb', 'Sandgrab', 'Bucle Arena', 'Tourbi-Sable', 'Sabbiotomba', '', ''],
  '524': [
    'すなあらし (Suna Arashi)',
    'Sandstorm',
    'Sandsturm',
    'Tormenta Arena',
    'Tempête de Sable',
    'Terrempesta',
    '',
    '',
  ],
  '525': [
    '(Sappy Seed)',
    '(Sappy Seed)',
    '(Sappy Seed)',
    '(Sappy Seed)',
    '(Sappy Seed)',
    '(Sappy Seed)',
    '(Sappy Seed)',
    '(Sappy Seed)',
  ],
  '526': [
    '絶対捕食回転斬 (Zettai Hoshoku Kaitenzan)',
    'Savage Spin-Out',
    'Wirbelnder Insektenhieb',
    'Guadaña Sedosa',
    'Cocon Fatal',
    'Bozzolo Fatale',
    '',
    '',
  ],
  '527': ['ねっとう (Nettō)', 'Scald', 'Siedewasser', 'Escaldar', 'Ébullition', 'Idrovampata', '', ''],
  '528': ['こわいかお (Kowai Kao)', 'Scary Face', 'Grimasse', 'Cara Susto', 'Grimace', 'Visotruce', '', ''],
  '529': ['ひっかく (Hikkaku)', 'Scratch', 'Kratzer', 'Arañazo', 'Griffe', 'Graffio', '', ''],
  '530': ['いやなおと (Iyanaoto)', 'Screech', 'Kreideschrei', 'Chirrido', 'Grincement', 'Stridio', '', ''],
  '531': ['かえんだん (Kaendan)', 'Searing Shot', 'Flammenball', 'Bomba Ígnea', 'Incendie', 'Sparafuoco', '', ''],
  '532': [
    'サンシャインスマッシャー (Sunshine Smasher)',
    'Searing Sunraze Smash',
    'Schmetternde Sonnenwalze',
    'Embestida Solar',
    'Hélio-Choc Dévastateur',
    'Supercollisione Solare',
    '',
    '',
  ],
  '533': [
    'ひみつのちから (Himitsu no Chikara)',
    'Secret Power',
    'Geheimpower',
    'Daño Secreto',
    'Force Cachée',
    'Forzasegreta',
    '',
    '',
  ],
  '534': [
    'しんぴのつるぎ (Shinpi no Tsurugi)',
    'Secret Sword',
    'Mystoschwert',
    'Sable Místico',
    'Lame Ouinte',
    'Spadamistica',
    '',
    '',
  ],
  '535': [
    'タネばくだん (Tane Bakudan)',
    'Seed Bomb',
    'Samenbomben',
    'Bomba Germen',
    'Canon Graine',
    'Semebomba',
    '',
    '',
  ],
  '536': ['シードフレア (Seed Flare)', 'Seed Flare', 'Schocksamen', 'Fogonazo', 'Fulmigraine', 'Infuriaseme', '', ''],
  '537': [
    'ちきゅうなげ (Chikyuu Nage)',
    'Seismic Toss',
    'Geowurf',
    'Mov. Sísmico',
    'Frappe Atlas',
    'Movim. Sismico',
    '',
    '',
  ],
  '538': ['じばく (Jibaku)', 'Self-Destruct', 'Finale', 'Autodestruc', 'Destruction', 'Autodistruz.', '', ''],
  '539': [
    'シャドーボール (Shadow Ball)',
    'Shadow Ball',
    'Spukball',
    'Bola Sombra',
    "Ball'Ombre",
    'Palla Ombra',
    '',
    '',
  ],
  '540': [
    'シャドーボーン (Shadow Bone)',
    'Shadow Bone',
    'Schattenknochen',
    'Hueso Sombrío',
    "Os'Ombre",
    'Ossotetro',
    '',
    '',
  ],
  '541': [
    'シャドークロー (Shadow Claw)',
    'Shadow Claw',
    'Dunkelklaue',
    'Garra Umbría',
    'Griffe Ombre',
    'Ombrartigli',
    '',
    '',
  ],
  '542': [
    'シャドーダイブ (Shadow Dive)',
    'Shadow Force',
    'Schemenkraft',
    'Golpe Umbrío',
    'Revenant',
    'Oscurotuffo',
    '',
    '',
  ],
  '543': [
    'シャドーパンチ (Shadow Punch)',
    'Shadow Punch',
    'Finsterfaust',
    'Puño Sombra',
    'Poing Ombre',
    'Pugnodombra',
    '',
    '',
  ],
  '544': ['かげうち (Kageuchi)', 'Shadow Sneak', 'Schattenstoß', 'Sombra Vil', 'Ombre Portée', 'Furtivombra', '', ''],
  '545': ['かくばる (Kakubaru)', 'Sharpen', 'Schärfer', 'Afilar', 'Affûtage', 'Affilatore', '', ''],
  '546': [
    'マキシマムサイブレイカー (Maximum Psy Breaker)',
    'Shattered Psyche',
    'Psycho-Schmetterschlag',
    'Disruptor Psíquico',
    'Psycho-Pulvérisation EX',
    ' Impatto Psicocinetico',
    '',
    '',
  ],
  '547': ['ぜったいれいど (Zettai Reido)', 'Sheer Cold', 'Eiseskälte', 'Frío Polar', 'Glaciation', 'Purogelo', '', ''],
  '548': [
    'からをやぶる (Kara wo Yaburu)',
    'Shell Smash',
    'Hausbruch',
    'Rompecoraza',
    'Exuviation',
    'Gettaguscio',
    '',
    '',
  ],
  '549': [
    'トラップシェル (Trap Shell)',
    'Shell Trap',
    'Panzerfalle',
    'Coraza Trampa',
    'Carapiège',
    'Gusciotrappola',
    '',
    '',
  ],
  '550': [
    'ギアチェンジ (Gear Change)',
    'Shift Gear',
    'Gangwechsel',
    'Cambio de Marcha',
    'Changement Vitesse',
    'Cambiomarcia',
    '',
    '',
  ],
  '551': ['でんげきは (Dengekiha)', 'Shock Wave', 'Schockwelle', 'Onda Voltio', 'Onde de Choc', 'Ondashock', '', ''],
  '552': ['すなあつめ (Sunaatsume)', 'Shore Up', 'Sandsammler', 'Recogearena', "Amass'Sable", 'Sabbiaccumulo', '', ''],
  '553': [
    'シグナルビーム (Signal Beam)',
    'Signal Beam',
    'Ampelleuchte',
    'Doble Rayo',
    'Rayon Signal',
    'Segnoraggio',
    '',
    '',
  ],
  '554': [
    "ぎんいろのかぜ (Gin'iro no Kaze)",
    'Silver Wind',
    'Silberhauch',
    'Viento Plata',
    'Vent Argenté',
    'Ventargenteo',
    '',
    '',
  ],
  '555': [
    'シンプルビーム (Simple Beam)',
    'Simple Beam',
    'Wankelstrahl',
    'Onda Simple',
    'Rayon Simple',
    'Ondisinvolta',
    '',
    '',
  ],
  '556': ['うたう (Utau)', 'Sing', 'Gesang', 'Canto', 'Berceuse', 'Canto', '', ''],
  '557': [
    'シャドーアローズストライク (Shadow Arrows Strike)',
    'Sinister Arrow Raid',
    'Schatten-Pfeilregen',
    'Aluvión de Flechas Sombrías',
    'Fureur des Plumes Spectrales',
    'Dardoassalto Spettrale',
    '',
    '',
  ],
  '558': [
    '(Sizzly Slide)',
    '(Sizzly Slide)',
    '(Sizzly Slide)',
    '(Sizzly Slide)',
    '(Sizzly Slide)',
    '(Sizzly Slide)',
    '(Sizzly Slide)',
    '(Sizzly Slide)',
  ],
  '559': ['スケッチ (Sketch)', 'Sketch', 'Nachahmer', 'Esquema', 'Gribouille', 'Schizzo', '', ''],
  '560': ['スキルスワップ (Skill Swap)', 'Skill Swap', 'Wertewechsel', 'Intercambio', 'Échange', 'Baratto', '', ''],
  '561': [
    'ロケットずつき (Rocket Zutsuki)',
    'Skull Bash',
    'Schädelwumme',
    'Cabezazo',
    "Coud'Krâne",
    'Capocciata',
    '',
    '',
  ],
  '562': ['ゴッドバード (God Bird)', 'Sky Attack', 'Himmelsfeger', 'Ataque Aéreo', 'Piqué', 'Aeroattacco', '', ''],
  '563': [
    'フリーフォール (Free Fall)',
    'Sky Drop',
    'Freier Fall',
    'Caída Libre',
    'Chute Libre',
    'Cadutalibera',
    '',
    '',
  ],
  '564': [
    'スカイアッパー (Sky Upper)',
    'Sky Uppercut',
    'Himmelhieb',
    'Gancho Alto',
    'Stratopercut',
    'Stramontante',
    '',
    '',
  ],
  '565': ['なまける (Namakeru)', 'Slack Off', 'Tagedieb', 'Relajo', 'Paresse', 'Pigro', '', ''],
  '566': ['たたきつける (Tatakitsukeru)', 'Slam', 'Slam', 'Atizar', 'Souplesse', 'Schianto', '', ''],
  '567': ['きりさく (Kirisaku)', 'Slash', 'Schlitzer', 'Cuchillada', 'Tranche', 'Lacerazione', '', ''],
  '568': ['ねむりごな (Nemuri Gona)', 'Sleep Powder', 'Schlafpuder', 'Somnífero', 'Poudre Dodo', 'Sonnifero', '', ''],
  '569': ['ねごと (Negoto)', 'Sleep Talk', 'Schlafrede', 'Sonámbulo', 'Blabla Dodo', 'Sonnolalia', '', ''],
  '570': ['ヘドロこうげき (Hedoro Kōgeki)', 'Sludge', 'Schlammbad', 'Residuos', 'Détritus', 'Fango', '', ''],
  '571': [
    'ヘドロばくだん (Hedoro Bakudan)',
    'Sludge Bomb',
    'Matschbombe',
    'Bomba Lodo',
    'Bomb-Beurk',
    'Fangobomba',
    '',
    '',
  ],
  '572': [
    'ヘドロウェーブ (Herodo Wave)',
    'Sludge Wave',
    'Schlammwoge',
    'Onda Tóxica',
    'Cradovague',
    'Fangonda',
    '',
    '',
  ],
  '573': ['うちおとす (Uchiotosu)', 'Smack Down', 'Katapult', 'Antiaéreo', 'Anti-Air', 'Abbattimento', '', ''],
  '574': [
    'スマートホーン (Smart Horn)',
    'Smart Strike',
    'Schmalhorn',
    'Cuerno Certero',
    'Estocorne',
    'Sottilcorno',
    '',
    '',
  ],
  '575': ['きつけ (Kitsuke)', 'Smelling Salts', 'Riechsalz', 'Estímulo', 'Stimulant', 'Maniereforti', '', ''],
  '576': ['スモッグ (Smog)', 'Smog', 'Smog', 'Polución', 'Purédpois', 'Smog', '', ''],
  '577': ['えんまく (Enmaku)', 'Smokescreen', 'Rauchwolke', 'Pantalla Humo', 'Brouillard', 'Muro di Fumo', '', ''],
  '578': ['バークアウト (Bark Out)', 'Snarl', 'Standpauke', 'Alarido', 'Aboiement', 'Urlorabbia', '', ''],
  '579': ['よこどり (Yokodori)', 'Snatch', 'Übernahme', 'Robo', 'Saisie', 'Scippo', '', ''],
  '580': ['いびき (Ibiki)', 'Snore', 'Schnarcher', 'Ronquido', 'Ronflement', 'Russare', '', ''],
  '581': ['みずびたし (Mizubitashi)', 'Soak', 'Überflutung', 'Anegar', 'Détrempage', 'Inondazione', '', ''],
  '582': ['タマゴうみ (Tamago Umi)', 'Soft-Boiled', 'Weichei', 'Amortiguador', 'E-Coque', 'Covauova', '', ''],
  '583': [
    'ソーラービーム (Solar Beam)',
    'Solar Beam',
    'Solarstrahl',
    'Rayo Solar',
    'Lance-Soleil',
    'Solarraggio',
    '',
    '',
  ],
  '584': [
    'ソーラーブレード (Solar Blade)',
    'Solar Blade',
    'Solarklinge',
    'Cuchilla Solar',
    'Lame Solaire',
    'Lama Solare',
    '',
    '',
  ],
  '585': ['ソニックブーム (Sonic Boom)', 'Sonic Boom', 'Ultraschall', 'Bomba Sónica', 'Sonicboom', 'Sonicboom', '', ''],
  '586': [
    '七星奪魂腿 (Shichisei Dakkontai)',
    'Soul-Stealing 7-Star Strike',
    'Sternbild des Seelenraubes',
    'Constelación Robaalmas',
    'Fauche-Âme des Sept Étoiles',
    'Colpo Eptastellare Rubanima',
    '',
    '',
  ],
  '587': [
    'あくうせつだん (Akū Setsudan)',
    'Spacial Rend',
    'Raumschlag',
    'Corte Vacío',
    'Spatio-Rift',
    'Fendispazio',
    '',
    '',
  ],
  '588': ['スパーク (Spark)', 'Spark', 'Funkensprung', 'Chispa', 'Étincelle', 'Scintilla', '', ''],
  '589': [
    'うたかたのアリア (Utakata no Aria)',
    'Sparkling Aria',
    'Schaumserenade',
    'Aria Burbuja',
    "Aria de l'Écume",
    'Canto Effimero',
    '',
    '',
  ],
  '590': [
    '(Sparkly Swirl)',
    '(Sparkly Swirl)',
    '(Sparkly Swirl)',
    '(Sparkly Swirl)',
    '(Sparkly Swirl)',
    '(Sparkly Swirl)',
    '(Sparkly Swirl)',
    '(Sparkly Swirl)',
  ],
  '591': [
    'シャドースチール (Shadow Steal)',
    'Spectral Thief',
    'Diebesschatten',
    'Robasombra',
    'Clepto-Mânes',
    'Ombrafurto',
    '',
    '',
  ],
  '592': [
    'スピードスワップ (Speed Swap)',
    'Speed Swap',
    'Initiativetausch',
    'Cambia Velocidad',
    'Permuvitesse',
    'Velociscambio',
    '',
    '',
  ],
  '593': ['クモのす (Kumo no Su)', 'Spider Web', 'Spinnennetz', 'Telaraña', 'Toile', 'Ragnatela', '', ''],
  '594': ['とげキャノン (Toge Cano)', 'Spike Cannon', 'Dornkanone', 'Clavo Cañón', 'Picanon', 'Sparalance', '', ''],
  '595': ['まきびし (Makibishi)', 'Spikes', 'Stachler', 'Púas', 'Picots', 'Punte', '', ''],
  '596': [
    'ニードルガード (Needle Guard)',
    'Spiky Shield',
    'Schutzstacheln',
    'Barrera Espinosa',
    'Pico-Défense',
    'Agodifesa',
    '',
    '',
  ],
  '597': [
    'かげぬい (Kagenui)',
    'Spirit Shackle',
    'Schattenfessel',
    'Puntada Sombría',
    'Tisse Ombre',
    "Cucitura d'Ombra",
    '',
    '',
  ],
  '598': ['はきだす (Hakidasu)', 'Spit Up', 'Entfessler', 'Escupir', 'Relâche', 'Sfoghenergia', '', ''],
  '599': ['うらみ (Urami)', 'Spite', 'Groll', 'Rencor', 'Dépit', 'Dispetto', '', ''],
  '600': ['はねる (Haneru)', 'Splash', 'Platscher', 'Salpicadura', 'Trempette', 'Splash', '', ''],
  '601': [
    'ラジアルエッジストーム (Radial Edgestorm)',
    'Splintered Stormshards',
    'Fataler Steinregen',
    'Tempestad Rocosa',
    'Hurlement des Roches-Lames',
    'Litotempesta Radiale',
    '',
    '',
  ],
  '602': [
    '(Splishy Splash)',
    '(Splishy Splash)',
    '(Splishy Splash)',
    '(Splishy Splash)',
    '(Splishy Splash)',
    '(Splishy Splash)',
    '(Splishy Splash)',
    '(Splishy Splash)',
  ],
  '603': ['キノコのほうし (Kinoko no Hōshi)', 'Spore', 'Pilzspore', 'Espora', 'Spore', 'Spora', '', ''],
  '604': ['スポットライト (Spotlight)', 'Spotlight', 'Rampenlicht', 'Foco', 'Projecteur', 'Riflettore', '', ''],
  '605': [
    'ステルスロック (Stealth Rock)',
    'Stealth Rock',
    'Tarnsteine',
    'Trampa Rocas',
    'Piège de Roc',
    'Levitoroccia',
    '',
    '',
  ],
  '606': [
    'スチームバースト (Steam Burst)',
    'Steam Eruption',
    'Dampfschwall',
    'Chorro de Vapor',
    'Jet de Vapeur',
    'Vaporscoppio',
    '',
    '',
  ],
  '607': [
    'ハードローラー (Hard Roller)',
    'Steamroller',
    'Quetschwalze',
    'Rodillo Púas',
    'Bulldoboule',
    'Rulloduro',
    '',
    '',
  ],
  '608': [
    'はがねのつばさ (Hagane no Tsubasa)',
    'Steel Wing',
    'Stahlflügel',
    'Ala De Acero',
    "Aile d'Acier",
    'Alacciaio',
    '',
    '',
  ],
  '609': [
    'ねばねばネット (Nebaneba Net)',
    'Sticky Web',
    'Klebenetz',
    'Red Viscosa',
    'Toile Gluante',
    'Rete Vischiosa',
    '',
    '',
  ],
  '610': ['たくわえる (Takuwaeru)', 'Stockpile', 'Horter', 'Reserva', 'Stockage', 'Accumulo', '', ''],
  '611': [
    'ライトニングサーフライド (Lightning Surf Ride)',
    'Stoked Sparksurfer',
    'Blitz-Wellenritt',
    'Surfeo Galvánico',
    'Électro-Surf Survolté',
    'Elettrosurf Folgorante',
    '',
    '',
  ],
  '612': ['ふみつけ (Fumitsuke)', 'Stomp', 'Stampfer', 'Pisotón', 'Écrasement', 'Pestone', '', ''],
  '613': ['じたんだ (Jitanda)', 'Stomping Tantrum', 'Fruststampfer', 'Pataleta', 'Trépignement', 'Battipiedi', '', ''],
  '614': [
    'ストーンエッジ (Stone Edge)',
    'Stone Edge',
    'Steinkante',
    'Roca Afilada',
    'Lame de Roc',
    'Pietrataglio',
    '',
    '',
  ],
  '615': [
    'アシストパワー (Assist Power)',
    'Stored Power',
    'Kraftvorrat',
    'Poder Reserva',
    'Force Ajoutée',
    'Veicolaforza',
    '',
    '',
  ],
  '616': ['やまあらし (Yamaarashi)', 'Storm Throw', 'Bergsturm', 'Llave Corsé', 'Yama Arashi', 'Tempestretta', '', ''],
  '617': ['かいりき (Kairiki)', 'Strength', 'Stärke', 'Fuerza', 'Force', 'Forza', '', ''],
  '618': [
    'ちからをすいとる (Chikara o Suitoru)',
    'Strength Sap',
    'Kraftabsorber',
    'Absorbefuerza',
    'Vol-Force',
    'Assorbiforza',
    '',
    '',
  ],
  '619': ['いとをはく (Ito o Haku)', 'String Shot', 'Fadenschuss', 'Disp. Demora', 'Sécrétion', 'Millebave', '', ''],
  '620': ['わるあがき (Waruagaki)', 'Struggle', 'Verzweifler', 'Forcejeo', 'Lutte', 'Scontro', '', ''],
  '621': [
    'むしのていこう (Mushi no Teikō)',
    'Struggle Bug',
    'Käfertrutz',
    'Estoicismo',
    'Survinsecte',
    'Entomoblocco',
    '',
    '',
  ],
  '622': [
    'しびれごな (Shibire Gona)',
    'Stun Spore',
    'Stachelspore',
    'Paralizador',
    'Para-Spore',
    'Paralizzante',
    '',
    '',
  ],
  '623': ['じごくぐるま (Jigoku Guruma)', 'Submission', 'Überroller', 'Sumisión', 'Sacrifice', 'Sottomissione', '', ''],
  '624': ['みがわり (Migawari)', 'Substitute', 'Delegator', 'Sustituto', 'Clonage', 'Sostituto', '', ''],
  '625': [
    'レイジングジオフリーズ (Raging Geo-Freeze)',
    'Subzero Slammer',
    'Tobender Geofrost',
    'Crioaliento Despiadado',
    'Laser Cryogénique',
    'Criodistruzione Polare',
    '',
    '',
  ],
  '626': ['ふいうち (Fuiuchi)', 'Sucker Punch', 'Tiefschlag', 'Golpe Bajo', 'Coup Bas', 'Sbigoattacco', '', ''],
  '627': ['にほんばれ (Nihonbare)', 'Sunny Day', 'Sonnentag', 'Día Soleado', 'Zénith', 'Giornodisole', '', ''],
  '628': [
    'メテオドライブ (Meteor Drive)',
    'Sunsteel Strike',
    'Stahlgestirn',
    'Meteoimpacto',
    'Choc Météore',
    'Astrocarica',
    '',
    '',
  ],
  '629': [
    'いかりのまえば (Ikari no Maeba)',
    'Super Fang',
    'Superzahn',
    'Superdiente',
    'Croc Fatal',
    'Superzanna',
    '',
    '',
  ],
  '630': [
    'ばかぢから (Bakajikara)',
    'Superpower',
    'Kraftkoloss',
    'Fuerza Bruta',
    'Surpuissance',
    'Troppoforte',
    '',
    '',
  ],
  '631': ['ちょうおんぱ (Chōonpa)', 'Supersonic', 'Superschall', 'Supersónico', 'Ultrason', 'Supersuono', '', ''],
  '632': [
    'ファイナルダイブクラッシュ (Final Dive Crush)',
    'Supersonic Skystrike',
    'Finaler Steilflug',
    'Picado Supersónico',
    'Piqué Supersonique',
    'Picchiata Devastante',
    '',
    '',
  ],
  '633': ['なみのり (Naminori)', 'Surf', 'Surfer', 'Surf', 'Surf', 'Surf', '', ''],
  '634': ['いばる (Ibaru)', 'Swagger', 'Angeberei', 'Contoneo', 'Vantardise', 'Bullo', '', ''],
  '635': ['のみこむ (Nomikomu)', 'Swallow', 'Verzehrer', 'Tragar', 'Avale', 'Intoenergia', '', ''],
  '636': [
    'てんしのキッス (Tenshi no Kiss)',
    'Sweet Kiss',
    'Bitterkuss',
    'Beso Dulce',
    'Doux Baiser',
    'Dolcebacio',
    '',
    '',
  ],
  '637': ['あまいかおり (Amai Kaori)', 'Sweet Scent', 'Lockduft', 'Dulce Aroma', 'Doux Parfum', 'Profumino', '', ''],
  '638': ['スピードスター (Speed Star)', 'Swift', 'Sternschauer', 'Rapidez', 'Météores', 'Comete', '', ''],
  '639': ['すりかえ (Surikae)', 'Switcheroo', 'Wechseldich', 'Trapicheo', 'Passe-Passe', 'Rapidscambio', '', ''],
  '640': [
    'つるぎのまい (Tsurugi no Mai)',
    'Swords Dance',
    'Schwerttanz',
    'Danza Espada',
    'Danse-Lames',
    'Danzaspada',
    '',
    '',
  ],
  '641': [
    'シンクロノイズ (Synchronoise)',
    'Synchronoise',
    'Synchrolärm',
    'Sincrorruido',
    'Synchropeine',
    'Sincrumore',
    '',
    '',
  ],
  '642': ['こうごうせい (Kōgōsei)', 'Synthesis', 'Synthese', 'Síntesis', 'Synthèse', 'Sintesi', '', ''],
  '643': ['たいあたり (Taiatari)', 'Tackle', 'Tackle', 'Placaje', 'Charge', 'Azione', '', ''],
  '644': ['ほたるび (Hotarubi)', 'Tail Glow', 'Schweifglanz', 'Ráfaga', 'Lumiqueue', 'Codadiluce', '', ''],
  '645': [
    'スイープビンタ (Sweep Binta)',
    'Tail Slap',
    'Kehrschelle',
    'Plumerazo',
    'Plumo-Queue',
    'Spazzasberla',
    '',
    '',
  ],
  '646': ['しっぽをふる (Shippo o Furu)', 'Tail Whip', 'Rutenschlag', 'Látigo', 'Mimi-Queue', 'Colpocoda', '', ''],
  '647': ['おいかぜ (Oikaze)', 'Tailwind', 'Rückenwind', 'Viento Afín', 'Vent Arrière', 'Ventoincoda', '', ''],
  '648': ['とっしん (Tosshin)', 'Take Down', 'Bodycheck', 'Derribo', 'Bélier', 'Riduttore', '', ''],
  '649': ['ちょうはつ (Chōhatsu)', 'Taunt', 'Verhöhner', 'Mofa', 'Provoc', 'Provocazione', '', ''],
  '650': [
    'なみだめ (Namida Me)',
    'Tearful Look',
    'Tränendrüse',
    'Ojos Llorosos',
    "Larme à l'Œil",
    'Occhionilucidi',
    '',
    '',
  ],
  '651': [
    'テクノバスター (Techno Buster)',
    'Techno Blast',
    'Techblaster',
    'Tecno Shock',
    'Techno-Buster',
    'Tecnobotto',
    '',
    '',
  ],
  '652': [
    'ライジングランドオーバー (Rising Grand Over)',
    'Tectonic Rage',
    'Seismische Eruption',
    'Barrena Telúrica',
    'Éruption Géo-Sismique',
    'Furore della Terra',
    '',
    '',
  ],
  '653': [
    'フラフラダンス (Furafura Dance)',
    'Teeter Dance',
    'Taumeltanz',
    'Danza Caos',
    'Danse-Folle',
    'Strampadanza',
    '',
    '',
  ],
  '654': [
    'テレキネシス (Telekinesis)',
    'Telekinesis',
    'Telekinese',
    'Telequinesis',
    'Lévikinésie',
    'Telecinesi',
    '',
    '',
  ],
  '655': ['テレポート (Teleport)', 'Teleport', 'Teleport', 'Teletransporte', 'Téléport', 'Teletrasporto', '', ''],
  '656': ['どろぼう (Dorobō)', 'Thief', 'Raub', 'Ladrón', 'Larcin', 'Furto', '', ''],
  '657': [
    'サウザンアロー (Thousand Arrow)',
    'Thousand Arrows',
    'Tausend Pfeile',
    'Mil Flechas',
    'Myria-Flèches',
    'Mille Frecce',
    '',
    '',
  ],
  '658': [
    'サウザンウェーブ (Thousand Wave)',
    'Thousand Waves',
    'Tausend Wellen',
    'Mil Temblores',
    'Myria-Vagues',
    'Mille Onde',
    '',
    '',
  ],
  '659': ['あばれる (Abareru)', 'Thrash', 'Fuchtler', 'Golpe', 'Mania', 'Colpo', '', ''],
  '660': [
    'じごくづき (Jigokuzuki)',
    'Throat Chop',
    'Neck Strike',
    'Golpe Mordaza',
    'Exécu-Son',
    'Colpo Infernale',
    '',
    '',
  ],
  '661': ['かみなり (Kaminari)', 'Thunder', 'Donner', 'Trueno', 'Fatal-Foudre', 'Tuono', '', ''],
  '662': [
    'かみなりのキバ (Kaminari no Kiba)',
    'Thunder Fang',
    'Donnerzahn',
    'Colmillo Rayo',
    'Crocs Éclair',
    'Fulmindenti',
    '',
    '',
  ],
  '663': [
    'かみなりパンチ (Kaminari Punch)',
    'Thunder Punch',
    'Donnerschlag',
    'Puño Trueno',
    'Poing-Éclair',
    'Tuonopugno',
    '',
    '',
  ],
  '664': [
    'でんきショック (Denki Shock)',
    'Thunder Shock',
    'Donnerschock',
    'Impactrueno',
    'Éclair',
    'Tuonoshock',
    '',
    '',
  ],
  '665': ['でんじは (Denjiha)', 'Thunder Wave', 'Donnerwelle', 'Onda Trueno', 'Cage-Éclair', 'Tuononda', '', ''],
  '666': ['１０まんボルト (Jūman Volt)', 'Thunderbolt', 'Donnerblitz', 'Rayo', 'Tonnerre', 'Fulmine', '', ''],
  '667': ['くすぐる (Kusuguru)', 'Tickle', 'Spaßkanone', 'Cosquillas', 'Chatouille', 'Solletico', '', ''],
  '668': [
    'ひっくりかえす (Hikkurikaesu)',
    'Topsy-Turvy',
    'Invertigo',
    'Reversión',
    'Renversement',
    'Sottosopra',
    '',
    '',
  ],
  '669': ['いちゃもん (Ichamon)', 'Torment', 'Folterknecht', 'Tormento', 'Tourmente', 'Attaccalite', '', ''],
  '670': ['どくどく (Dokudoku)', 'Toxic', 'Toxin', 'Tóxico', 'Toxik', 'Tossina', '', ''],
  '671': ['どくびし (Dokubishi)', 'Toxic Spikes', 'Giftspitzen', 'Púas Tóxicas', 'Pics Toxik', 'Fielepunte', '', ''],
  '672': [
    'どくのいと (Doku no Ito)',
    'Toxic Thread',
    'Giftfaden',
    'Hilo Venenoso',
    'Fil Toxique',
    'Velenotela',
    '',
    '',
  ],
  '673': ['へんしん (Henshin)', 'Transform', 'Wandler', 'Transformación', 'Morphing', 'Trasformazione', '', ''],
  '674': ['トライアタック (Tri Attack)', 'Tri Attack', 'Triplette', 'Triataque', 'Triplattaque', 'Tripletta', '', ''],
  '675': ['トリック (Trick)', 'Trick', 'Trickbetrug', 'Truco', 'Tourmagik', 'Raggiro', '', ''],
  '676': [
    'トリックルーム (Trick Room)',
    'Trick Room',
    'Bizarroraum',
    'Espacio Raro',
    'Distorsion',
    'Distortozona',
    '',
    '',
  ],
  '677': ['ハロウィン (Halloween)', 'Trick-or-Treat', 'Halloween', 'Halloween', 'Halloween', 'Halloween', '', ''],
  '678': [
    'トリプルキック (Triple Kick)',
    'Triple Kick',
    'Dreifachkick',
    'Triple Patada',
    'Triple Pied',
    'Triplocalcio',
    '',
    '',
  ],
  '679': [
    'トロピカルキック (Tropical Kick)',
    'Trop Kick',
    'Tropenkick',
    'Patada Tropica',
    'Botte Sucrette',
    'Tropicalcio',
    '',
    '',
  ],
  '680': ['きりふだ (Kirifuda)', 'Trump Card', 'Trumpfkarte', 'As Oculto', 'Atout', 'Asso', '', ''],
  '681': [
    'ダブルニードル (Double Needle)',
    'Twineedle',
    'Duonadel',
    'Doble Ataque',
    'Double-Dard',
    'Doppio Ago',
    '',
    '',
  ],
  '682': [
    'ラブリースターインパクト (Lovely Star Impact)',
    'Twinkle Tackle',
    'Entzückender Sternenstoß',
    'Arrumaco Sideral',
    'Impact Choupinova',
    'Astroimpatto Fatato',
    '',
    '',
  ],
  '683': ['たつまき (Tatsumaki)', 'Twister', 'Windhose', 'Ciclón', 'Ouragan', 'Tornado', '', ''],
  '684': ['とんぼがえり (Tonbo Gaeri)', 'U-turn', 'Kehrtwende', 'Ida y Vuelta', 'Demi-Tour', 'Retromarcia', '', ''],
  '685': ['さわぐ (Sawagu)', 'Uproar', 'Aufruhr', 'Alboroto', 'Brouhaha', 'Baraonda', '', ''],
  '686': [
    'Ｖジェネレート (V-Generate)',
    'V-create',
    'V-Generator',
    'V de Fuego',
    'Coup Victoire',
    'Generatore V',
    '',
    '',
  ],
  '687': ['しんくうは (Shinkū Ha)', 'Vacuum Wave', 'Vakuumwelle', 'Onda Vacío', 'Onde Vide', 'Vuotonda', '', ''],
  '688': [
    '(Veevee Volley)',
    '(Veevee Volley)',
    '(Veevee Volley)',
    '(Veevee Volley)',
    '(Veevee Volley)',
    '(Veevee Volley)',
    '(Veevee Volley)',
    '(Veevee Volley)',
  ],
  '689': [
    'ベノムトラップ (Venom Trap)',
    'Venom Drench',
    'Giftfalle',
    'Trampa Venenosa',
    'Piège de Venin',
    'Velenotrappola',
    '',
    '',
  ],
  '690': [
    'ベノムショック (Venom Shock)',
    'Venoshock',
    'Giftschock',
    'Cargatóxica',
    'Choc Venin',
    'Velenoshock',
    '',
    '',
  ],
  '691': ['はさむ (Hasamu)', 'Vice Grip', 'Klammer', 'Agarre', 'Force Poigne', 'Presa', '', ''],
  '692': ['つるのムチ (Tsuru no Muchi)', 'Vine Whip', 'Rankenhieb', 'Látigo Cepa', 'Fouet Lianes', 'Frustata', '', ''],
  '693': ['あてみなげ (Ateminage)', 'Vital Throw', 'Überwurf', 'Tiro Vital', 'Corps Perdu', 'Vitaltiro', '', ''],
  '694': [
    'ボルトチェンジ (Volt Change)',
    'Volt Switch',
    'Voltwechsel',
    'Voltiocambio',
    'Change Éclair',
    'Invertivolt',
    '',
    '',
  ],
  '695': [
    'ボルテッカー (Volteccer)',
    'Volt Tackle',
    'Volttackle',
    'Placaje Eléctrico',
    'Électacle',
    'Locomovolt',
    '',
    '',
  ],
  '696': [
    'めざましビンタ (Mezamashi Binta)',
    'Wake-Up Slap',
    'Weckruf',
    'Espabila',
    'Réveil Forcé',
    'Svegliopacca',
    '',
    '',
  ],
  '697': [
    'みずでっぽう (Mizu Deppō)',
    'Water Gun',
    'Aquaknarre',
    'Pistola Agua',
    'Pistolet à O',
    'Pistolacqua',
    '',
    '',
  ],
  '698': [
    'みずのちかい (Mizu no Chikai)',
    'Water Pledge',
    'Wassersäulen',
    'Voto Agua',
    "Aire d'Eau",
    'Acquapatto',
    '',
    '',
  ],
  '699': ['みずのはどう (Mizu no Hadō)', 'Water Pulse', 'Aquawelle', 'Hidropulso', 'Vibraqua', 'Idropulsar', '', ''],
  '700': [
    'みずしゅりけん (Mizu Shuriken)',
    'Water Shuriken',
    'Wasser-Shuriken',
    'Shuriken de Agua',
    'Sheauriken',
    'Acqualame',
    '',
    '',
  ],
  '701': ['みずあそび (Mizu Asobi)', 'Water Sport', 'Nassmacher', 'Hidrochorro', 'Tourniquet', 'Docciascudo', '', ''],
  '702': ['しおふき (Shiofuki)', 'Water Spout', 'Fontränen', 'Salpicar', 'Giclédo', 'Zampillo', '', ''],
  '703': ['たきのぼり (Taki Nobori)', 'Waterfall', 'Kaskade', 'Cascada', 'Cascade', 'Cascata', '', ''],
  '704': [
    'ウェザーボール (Weather Ball)',
    'Weather Ball',
    'Meteorologe',
    'Meteorobola',
    "Ball'Météo",
    'Palla Clima',
    '',
    '',
  ],
  '705': ['うずしお (Uzushio)', 'Whirlpool', 'Whirlpool', 'Torbellino', 'Siphon', 'Mulinello', '', ''],
  '706': ['ふきとばし (Fukitobashi)', 'Whirlwind', 'Wirbelwind', 'Remolino', 'Cyclone', 'Turbine', '', ''],
  '707': [
    'ワイドガード (Wide Guard)',
    'Wide Guard',
    'Rundumschutz',
    'Vastaguardia',
    'Garde Large',
    'Bodyguard',
    '',
    '',
  ],
  '708': [
    'ワイルドボルト (Wild Volt)',
    'Wild Charge',
    'Stromstoß',
    'Voltio Cruel',
    'Éclair Fou',
    'Sprizzalampo',
    '',
    '',
  ],
  '709': ['おにび (Onibi)', 'Will-O-Wisp', 'Irrlicht', 'Fuego Fatuo', 'Feu Follet', 'Fuocofatuo', '', ''],
  '710': [
    'つばさでうつ (Tsubasa de Utsu)',
    'Wing Attack',
    'Flügelschlag',
    'Ataque Ala',
    'Cru-Aile',
    "Attacco d'Ala",
    '',
    '',
  ],
  '711': ['ねがいごと (Negaigoto)', 'Wish', 'Wunschtraum', 'Deseo', 'Vœu', 'Desiderio', '', ''],
  '712': ['からにこもる (Kara ni Komoru)', 'Withdraw', 'Panzerschutz', 'Refugio', 'Repli', 'Ritirata', '', ''],
  '713': [
    'ワンダールーム (Wonder Room)',
    'Wonder Room',
    'Wunderraum',
    'Zona Extraña',
    'Zone Étrange',
    'Mirabilzona',
    '',
    '',
  ],
  '714': ['ウッドハンマー (Wood Hammer)', 'Wood Hammer', 'Holzhammer', 'Mazazo', 'Martobois', 'Mazzuolegno', '', ''],
  '715': ['ふるいたてる (Furui Tateru)', 'Work Up', 'Kraftschub', 'Avivar', 'Rengorgement', 'Cuordileone', '', ''],
  '716': [
    'なやみのタネ (Nayami no Tane)',
    'Worry Seed',
    'Sorgensamen',
    'Abatidoras',
    'Soucigraine',
    'Affannoseme',
    '',
    '',
  ],
  '717': ['まきつく (Makitsuku)', 'Wrap', 'Wickel', 'Constricción', 'Ligotage', 'Avvolgibotta', '', ''],
  '718': ['しぼりとる (Shiboritoru)', 'Wring Out', 'Auswringen', 'Estrujón', 'Essorage', 'Strizzata', '', ''],
  '719': ['シザークロス (Scissor Cross)', 'X-Scissor', 'Kreuzschere', 'Tijera X', 'Plaie-Croix', 'Forbice X', '', ''],
  '720': ['あくび (Akubi)', 'Yawn', 'Gähner', 'Bostezo', 'Bâillement', 'Sbadiglio', '', ''],
  '721': ['でんじほう (Denjihō)', 'Zap Cannon', 'Blitzkanone', 'Electrocañón', 'Élecanon', 'Falcecannone', '', ''],
  '722': [
    'しねんのずつき (Shinen no Zutsuki)',
    'Zen Headbutt',
    'Zen-Kopfstoß',
    'Cabezazo Zen',
    "Psykoud'Boul",
    'Cozzata Zen',
    '',
    '',
  ],
  '723': [
    'びりびりちくちく (Biribiri Chikuchiku)',
    'Zing Zap',
    'Elektropikser',
    'Electropunzada',
    'Électrikipik',
    'Elettropizzico',
    '',
    '',
  ],
  '724': [
    '(Zippy Zap)',
    '(Zippy Zap)',
    '(Zippy Zap)',
    '(Zippy Zap)',
    '(Zippy Zap)',
    '(Zippy Zap)',
    '(Zippy Zap)',
    '(Zippy Zap)',
  ],
};

export const getMoveName = (id: string, locale: number) => moveNames[id][locale] || '';
